//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Achievement.proto
namespace Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CAchievementRequest")]
  public partial class CS_CAchievementRequest : global::ProtoBuf.IExtensible
  {
    public CS_CAchievementRequest() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }

    private int _title = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int title
    {
      get { return _title; }
      set { _title = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AchievementInfoResponse")]
  public partial class SC_AchievementInfoResponse : global::ProtoBuf.IExtensible
  {
    public SC_AchievementInfoResponse() {}
    
    private int _point;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int point
    {
      get { return _point; }
      set { _point = value; }
    }

    private int _title = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int title
    {
      get { return _title; }
      set { _title = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AchievementTitleItemResponse")]
  public partial class SC_AchievementTitleItemResponse : global::ProtoBuf.IExtensible
  {
    public SC_AchievementTitleItemResponse() {}
    
    private int _title;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int title
    {
      get { return _title; }
      set { _title = value; }
    }

    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AchievementTitleListResponse")]
  public partial class SC_AchievementTitleListResponse : global::ProtoBuf.IExtensible
  {
    public SC_AchievementTitleListResponse() {}
    
    private readonly global::System.Collections.Generic.List<Msg.SC_AchievementTitleItemResponse> _list = new global::System.Collections.Generic.List<Msg.SC_AchievementTitleItemResponse>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Msg.SC_AchievementTitleItemResponse> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AchievementTitleAddResponse")]
  public partial class SC_AchievementTitleAddResponse : global::ProtoBuf.IExtensible
  {
    public SC_AchievementTitleAddResponse() {}
    
    private int _title;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int title
    {
      get { return _title; }
      set { _title = value; }
    }

    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}