//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: activity.proto
// Note: requires additional types generated from: item.proto
namespace network
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_activity_config_info_update")]
  public partial class sc_activity_config_info_update : global::ProtoBuf.IExtensible
  {
    public sc_activity_config_info_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_activity_config> _activity_list = new global::System.Collections.Generic.List<network.pb_activity_config>();
    [global::ProtoBuf.ProtoMember(1, Name=@"activity_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_activity_config> activity_list
    {
      get { return _activity_list; }
    }
  
    private uint _hide_function_flag;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hide_function_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hide_function_flag
    {
      get { return _hide_function_flag; }
      set { _hide_function_flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_activity_config")]
  public partial class pb_activity_config : global::ProtoBuf.IExtensible
  {
    public pb_activity_config() {}
    
    private network.pb_activity_data _activity_data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"activity_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public network.pb_activity_data activity_data
    {
      get { return _activity_data; }
      set { _activity_data = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_sub_activity_config> _sub_list = new global::System.Collections.Generic.List<network.pb_sub_activity_config>();
    [global::ProtoBuf.ProtoMember(2, Name=@"sub_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_sub_activity_config> sub_list
    {
      get { return _sub_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_sub_activity_config")]
  public partial class pb_sub_activity_config : global::ProtoBuf.IExtensible
  {
    public pb_sub_activity_config() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong data
    {
      get { return _data; }
      set { _data = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _reward_list = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"reward_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> reward_list
    {
      get { return _reward_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_activity_data")]
  public partial class pb_activity_data : global::ProtoBuf.IExtensible
  {
    public pb_activity_data() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _current_data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"current_data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong current_data
    {
      get { return _current_data; }
      set { _current_data = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _draw_info_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"draw_info_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> draw_info_list
    {
      get { return _draw_info_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_activity_info_query_req")]
  public partial class cs_activity_info_query_req : global::ProtoBuf.IExtensible
  {
    public cs_activity_info_query_req() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_activity_info_query_reply")]
  public partial class sc_activity_info_query_reply : global::ProtoBuf.IExtensible
  {
    public sc_activity_info_query_reply() {}
    
    private network.pb_activity_data _activity_data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"activity_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public network.pb_activity_data activity_data
    {
      get { return _activity_data; }
      set { _activity_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_activity_draw_req")]
  public partial class cs_activity_draw_req : global::ProtoBuf.IExtensible
  {
    public cs_activity_draw_req() {}
    
    private uint _activity_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"activity_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint activity_id
    {
      get { return _activity_id; }
      set { _activity_id = value; }
    }
    private uint _sub_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sub_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sub_id
    {
      get { return _sub_id; }
      set { _sub_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_activity_draw_reply")]
  public partial class sc_activity_draw_reply : global::ProtoBuf.IExtensible
  {
    public sc_activity_draw_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private byte[] _err;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _reward_list = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"reward_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> reward_list
    {
      get { return _reward_list; }
    }
  
    private uint _activity_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"activity_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint activity_id
    {
      get { return _activity_id; }
      set { _activity_id = value; }
    }
    private uint _sub_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sub_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sub_id
    {
      get { return _sub_id; }
      set { _sub_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_annoucement_config")]
  public partial class pb_annoucement_config : global::ProtoBuf.IExtensible
  {
    public pb_annoucement_config() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _title;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] title
    {
      get { return _title; }
      set { _title = value; }
    }
    private byte[] _content;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}