//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Analys.proto
namespace Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"lua_nested")]
  public partial class lua_nested : global::ProtoBuf.IExtensible
  {
    public lua_nested() {}
    
    private int _value_int32;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value_int32", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value_int32
    {
      get { return _value_int32; }
      set { _value_int32 = value; }
    }
    private bool _value_bool;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value_bool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool value_bool
    {
      get { return _value_bool; }
      set { _value_bool = value; }
    }
    private string _value_string;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"value_string", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value_string
    {
      get { return _value_string; }
      set { _value_string = value; }
    }
    private byte[] _value_bytes;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"value_bytes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] value_bytes
    {
      get { return _value_bytes; }
      set { _value_bytes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"lua_message")]
  public partial class lua_message : global::ProtoBuf.IExtensible
  {
    public lua_message() {}
    
    private readonly global::System.Collections.Generic.List<Msg.lua_nested> _value_repeated = new global::System.Collections.Generic.List<Msg.lua_nested>();
    [global::ProtoBuf.ProtoMember(1, Name=@"value_repeated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Msg.lua_nested> value_repeated
    {
      get { return _value_repeated; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"lua_message2")]
  public partial class lua_message2 : global::ProtoBuf.IExtensible
  {
    public lua_message2() {}
    
    private int _value_int32;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value_int32", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value_int32
    {
      get { return _value_int32; }
      set { _value_int32 = value; }
    }
    private uint _value_uint32;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value_uint32", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint value_uint32
    {
      get { return _value_uint32; }
      set { _value_uint32 = value; }
    }
    private long _value_int64;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"value_int64", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long value_int64
    {
      get { return _value_int64; }
      set { _value_int64 = value; }
    }
    private ulong _value_uint64;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"value_uint64", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong value_uint64
    {
      get { return _value_uint64; }
      set { _value_uint64 = value; }
    }

    private bool _value_bool = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"value_bool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool value_bool
    {
      get { return _value_bool; }
      set { _value_bool = value; }
    }
    private byte[] _value_bytes;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"value_bytes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] value_bytes
    {
      get { return _value_bytes; }
      set { _value_bytes = value; }
    }
    private float _value_float;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"value_float", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float value_float
    {
      get { return _value_float; }
      set { _value_float = value; }
    }
    private double _value_double;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"value_double", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double value_double
    {
      get { return _value_double; }
      set { _value_double = value; }
    }
    private string _value_string;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"value_string", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value_string
    {
      get { return _value_string; }
      set { _value_string = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}