//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Battle.proto
namespace Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CBattleEnterRequest")]
  public partial class CS_CBattleEnterRequest : global::ProtoBuf.IExtensible
  {
    public CS_CBattleEnterRequest() {}
    
    private int _stage;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stage
    {
      get { return _stage; }
      set { _stage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CBattleExitRequest")]
  public partial class CS_CBattleExitRequest : global::ProtoBuf.IExtensible
  {
    public CS_CBattleExitRequest() {}
    
    private int _stage;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stage
    {
      get { return _stage; }
      set { _stage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CBattleSlotRequest")]
  public partial class CS_CBattleSlotRequest : global::ProtoBuf.IExtensible
  {
    public CS_CBattleSlotRequest() {}
    
    private int _slot;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int slot
    {
      get { return _slot; }
      set { _slot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CBattleLaunchRequest")]
  public partial class CS_CBattleLaunchRequest : global::ProtoBuf.IExtensible
  {
    public CS_CBattleLaunchRequest() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }

    private int _y = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }

    private int _z = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CBattleFishDieRequest")]
  public partial class CS_CBattleFishDieRequest : global::ProtoBuf.IExtensible
  {
    public CS_CBattleFishDieRequest() {}
    
    private int _fishId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CBattleUserAttackRequest")]
  public partial class CS_CBattleUserAttackRequest : global::ProtoBuf.IExtensible
  {
    public CS_CBattleUserAttackRequest() {}
    
    private readonly global::System.Collections.Generic.List<int> _fishId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> fishId
    {
      get { return _fishId; }
    }
  

    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CBattleChangeLvRequest")]
  public partial class CS_CBattleChangeLvRequest : global::ProtoBuf.IExtensible
  {
    public CS_CBattleChangeLvRequest() {}
    
    private int _lv;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CBattlePickupRequest")]
  public partial class CS_CBattlePickupRequest : global::ProtoBuf.IExtensible
  {
    public CS_CBattlePickupRequest() {}
    
    private int _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CBattleSynInfoRequest")]
  public partial class CS_CBattleSynInfoRequest : global::ProtoBuf.IExtensible
  {
    public CS_CBattleSynInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CBattleFishDisappearRequest")]
  public partial class CS_CBattleFishDisappearRequest : global::ProtoBuf.IExtensible
  {
    public CS_CBattleFishDisappearRequest() {}
    
    private int _fishId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CBattleHurtRequest")]
  public partial class CS_CBattleHurtRequest : global::ProtoBuf.IExtensible
  {
    public CS_CBattleHurtRequest() {}
    
    private int _fishId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }

    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CBattlChangeSkinRequest")]
  public partial class CS_CBattlChangeSkinRequest : global::ProtoBuf.IExtensible
  {
    public CS_CBattlChangeSkinRequest() {}
    
    private int _skinId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skinId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skinId
    {
      get { return _skinId; }
      set { _skinId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleEnterResponse")]
  public partial class SC_CBattleEnterResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleEnterResponse() {}
    
    private int _stage;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stage
    {
      get { return _stage; }
      set { _stage = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleExitResponse")]
  public partial class SC_CBattleExitResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleExitResponse() {}
    
    private int _stage;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stage
    {
      get { return _stage; }
      set { _stage = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleSlotResponse")]
  public partial class SC_CBattleSlotResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleSlotResponse() {}
    
    private int _slot;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int slot
    {
      get { return _slot; }
      set { _slot = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _gunLv = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gunLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gunLv
    {
      get { return _gunLv; }
      set { _gunLv = value; }
    }

    private int _gunLife = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gunLife", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gunLife
    {
      get { return _gunLife; }
      set { _gunLife = value; }
    }

    private int _gunSkinId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gunSkinId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gunSkinId
    {
      get { return _gunSkinId; }
      set { _gunSkinId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleLaunchResponse")]
  public partial class SC_CBattleLaunchResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleLaunchResponse() {}
    
    private int _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }

    private string _userId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _x = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }

    private int _y = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }

    private int _z = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleDieItemResponse")]
  public partial class SC_CBattleDieItemResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleDieItemResponse() {}
    
    private int _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _itemType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemType
    {
      get { return _itemType; }
      set { _itemType = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleFishDieResponse")]
  public partial class SC_CBattleFishDieResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleFishDieResponse() {}
    
    private int _fishId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _money = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }

    private int _emoney = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"emoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int emoney
    {
      get { return _emoney; }
      set { _emoney = value; }
    }
    private readonly global::System.Collections.Generic.List<Msg.SC_CBattleDieItemResponse> _item = new global::System.Collections.Generic.List<Msg.SC_CBattleDieItemResponse>();
    [global::ProtoBuf.ProtoMember(5, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Msg.SC_CBattleDieItemResponse> item
    {
      get { return _item; }
    }
  

    private int _drop = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"drop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int drop
    {
      get { return _drop; }
      set { _drop = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleSlotItemResponse")]
  public partial class SC_CBattleSlotItemResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleSlotItemResponse() {}
    
    private int _slot;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int slot
    {
      get { return _slot; }
      set { _slot = value; }
    }

    private string _userId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _gunLv = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gunLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gunLv
    {
      get { return _gunLv; }
      set { _gunLv = value; }
    }

    private int _gunLife = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gunLife", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gunLife
    {
      get { return _gunLife; }
      set { _gunLife = value; }
    }

    private int _skinId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"skinId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skinId
    {
      get { return _skinId; }
      set { _skinId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleInfoResponse")]
  public partial class SC_CBattleInfoResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleInfoResponse() {}
    
    private int _createTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private int _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<Msg.SC_CBattleSlotItemResponse> _slots = new global::System.Collections.Generic.List<Msg.SC_CBattleSlotItemResponse>();
    [global::ProtoBuf.ProtoMember(3, Name=@"slots", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Msg.SC_CBattleSlotItemResponse> slots
    {
      get { return _slots; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleFishCreateResponse")]
  public partial class SC_CBattleFishCreateResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleFishCreateResponse() {}
    
    private int _fishId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }

    private int _fishTypeId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fishTypeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fishTypeId
    {
      get { return _fishTypeId; }
      set { _fishTypeId = value; }
    }

    private int _fishGenTime = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fishGenTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fishGenTime
    {
      get { return _fishGenTime; }
      set { _fishGenTime = value; }
    }

    private int _fishPathId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fishPathId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fishPathId
    {
      get { return _fishPathId; }
      set { _fishPathId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _coordinate = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"coordinate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> coordinate
    {
      get { return _coordinate; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _buffs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"buffs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> buffs
    {
      get { return _buffs; }
    }
  

    private int _finishTime = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"finishTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int finishTime
    {
      get { return _finishTime; }
      set { _finishTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleFishSkillResponse")]
  public partial class SC_CBattleFishSkillResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleFishSkillResponse() {}
    
    private int _fishId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }

    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _targets = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"targets", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> targets
    {
      get { return _targets; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleUserAttackResponse")]
  public partial class SC_CBattleUserAttackResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleUserAttackResponse() {}
    
    private int _fishId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleNextWaveResponse")]
  public partial class SC_CBattleNextWaveResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleNextWaveResponse() {}
    
    private int _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }

    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleChangeLvResponse")]
  public partial class SC_CBattleChangeLvResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleChangeLvResponse() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _lv = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleLifeResponse")]
  public partial class SC_CBattleLifeResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleLifeResponse() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _life = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"life", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int life
    {
      get { return _life; }
      set { _life = value; }
    }

    private int _hurt = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hurt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hurt
    {
      get { return _hurt; }
      set { _hurt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleStatusResponse")]
  public partial class SC_CBattleStatusResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleStatusResponse() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _skillIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"skillIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> skillIds
    {
      get { return _skillIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleStatusDelResponse")]
  public partial class SC_CBattleStatusDelResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleStatusDelResponse() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _skillIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"skillIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> skillIds
    {
      get { return _skillIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleChangeSkinResponse")]
  public partial class SC_CBattleChangeSkinResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleChangeSkinResponse() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _skinId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skinId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skinId
    {
      get { return _skinId; }
      set { _skinId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleMermaidResponse")]
  public partial class SC_CBattleMermaidResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleMermaidResponse() {}
    
    private int _scoreHour;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"scoreHour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int scoreHour
    {
      get { return _scoreHour; }
      set { _scoreHour = value; }
    }

    private int _rankHour = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rankHour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rankHour
    {
      get { return _rankHour; }
      set { _rankHour = value; }
    }

    private int _preRankHour = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"preRankHour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int preRankHour
    {
      get { return _preRankHour; }
      set { _preRankHour = value; }
    }

    private int _scoreDay = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"scoreDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int scoreDay
    {
      get { return _scoreDay; }
      set { _scoreDay = value; }
    }

    private int _rankDay = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rankDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rankDay
    {
      get { return _rankDay; }
      set { _rankDay = value; }
    }

    private int _preRankDay = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"preRankDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int preRankDay
    {
      get { return _preRankDay; }
      set { _preRankDay = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleMermaidItemResponse")]
  public partial class SC_CBattleMermaidItemResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleMermaidItemResponse() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }

    private int _rank = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }

    private int _head = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int head
    {
      get { return _head; }
      set { _head = value; }
    }

    private int _headFrame = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"headFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headFrame
    {
      get { return _headFrame; }
      set { _headFrame = value; }
    }

    private int _title = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int title
    {
      get { return _title; }
      set { _title = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CBattleMermaidRankResponse")]
  public partial class SC_CBattleMermaidRankResponse : global::ProtoBuf.IExtensible
  {
    public SC_CBattleMermaidRankResponse() {}
    
    private readonly global::System.Collections.Generic.List<Msg.SC_CBattleMermaidItemResponse> _listHour = new global::System.Collections.Generic.List<Msg.SC_CBattleMermaidItemResponse>();
    [global::ProtoBuf.ProtoMember(1, Name=@"listHour", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Msg.SC_CBattleMermaidItemResponse> listHour
    {
      get { return _listHour; }
    }
  
    private readonly global::System.Collections.Generic.List<Msg.SC_CBattleMermaidItemResponse> _listDay = new global::System.Collections.Generic.List<Msg.SC_CBattleMermaidItemResponse>();
    [global::ProtoBuf.ProtoMember(2, Name=@"listDay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Msg.SC_CBattleMermaidItemResponse> listDay
    {
      get { return _listDay; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}