//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: car.proto
// Note: requires additional types generated from: item.proto
namespace network
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_car_enter_req")]
  public partial class cs_car_enter_req : global::ProtoBuf.IExtensible
  {
    public cs_car_enter_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_enter_reply")]
  public partial class sc_car_enter_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_enter_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_car_exit_req")]
  public partial class cs_car_exit_req : global::ProtoBuf.IExtensible
  {
    public cs_car_exit_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_exit_reply")]
  public partial class sc_car_exit_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_exit_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_car_master_req")]
  public partial class cs_car_master_req : global::ProtoBuf.IExtensible
  {
    public cs_car_master_req() {}
    
    private int _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private int _money;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_master_reply")]
  public partial class sc_car_master_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_master_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private int _flag;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_car_bet_req")]
  public partial class cs_car_bet_req : global::ProtoBuf.IExtensible
  {
    public cs_car_bet_req() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _money;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_bet_reply")]
  public partial class sc_car_bet_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_bet_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private int _index;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _money;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _self;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"self", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int self
    {
      get { return _self; }
      set { _self = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_car_rebet_req")]
  public partial class cs_car_rebet_req : global::ProtoBuf.IExtensible
  {
    public cs_car_rebet_req() {}
    
    private readonly global::System.Collections.Generic.List<network.cs_car_bet_req> _list = new global::System.Collections.Generic.List<network.cs_car_bet_req>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.cs_car_bet_req> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_rebet_reply")]
  public partial class sc_car_rebet_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_rebet_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<network.sc_car_bet_reply> _list = new global::System.Collections.Generic.List<network.sc_car_bet_reply>();
    [global::ProtoBuf.ProtoMember(3, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.sc_car_bet_reply> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_car_master_list_req")]
  public partial class cs_car_master_list_req : global::ProtoBuf.IExtensible
  {
    public cs_car_master_list_req() {}
    
    private int _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_car_master_item")]
  public partial class pb_car_master_item : global::ProtoBuf.IExtensible
  {
    public pb_car_master_item() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _money;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _vip;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_car_user_list_req")]
  public partial class cs_car_user_list_req : global::ProtoBuf.IExtensible
  {
    public cs_car_user_list_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_user_list_reply")]
  public partial class sc_car_user_list_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_user_list_reply() {}
    
    private int _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_car_user_item> _list = new global::System.Collections.Generic.List<network.pb_car_user_item>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_car_user_item> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_car_user_item")]
  public partial class pb_car_user_item : global::ProtoBuf.IExtensible
  {
    public pb_car_user_item() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _money;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _vip;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private string _head;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string head
    {
      get { return _head; }
      set { _head = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_result_history_req")]
  public partial class sc_car_result_history_req : global::ProtoBuf.IExtensible
  {
    public sc_car_result_history_req() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_car_result_history_item> _list = new global::System.Collections.Generic.List<network.pb_car_result_history_item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_car_result_history_item> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_car_result_history_item")]
  public partial class pb_car_result_history_item : global::ProtoBuf.IExtensible
  {
    public pb_car_result_history_item() {}
    
    private string _open_index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"open_index", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string open_index
    {
      get { return _open_index; }
      set { _open_index = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _pool;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pool", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pool
    {
      get { return _pool; }
      set { _pool = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_master_wait_list_reply")]
  public partial class sc_car_master_wait_list_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_master_wait_list_reply() {}
    
    private int _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_car_master_item> _list = new global::System.Collections.Generic.List<network.pb_car_master_item>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_car_master_item> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_master_info_reply")]
  public partial class sc_car_master_info_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_master_info_reply() {}
    
    private int _self;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"self", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int self
    {
      get { return _self; }
      set { _self = value; }
    }
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _money;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private string _head;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string head
    {
      get { return _head; }
      set { _head = value; }
    }
    private int _vip;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_status_reply")]
  public partial class sc_car_status_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_status_reply() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_car_bet_item")]
  public partial class pb_car_bet_item : global::ProtoBuf.IExtensible
  {
    public pb_car_bet_item() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _money;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_room_info_reply")]
  public partial class sc_car_room_info_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_room_info_reply() {}
    
    private network.sc_car_master_info_reply _masterInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"masterInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public network.sc_car_master_info_reply masterInfo
    {
      get { return _masterInfo; }
      set { _masterInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_car_bet_item> _list = new global::System.Collections.Generic.List<network.pb_car_bet_item>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_car_bet_item> list
    {
      get { return _list; }
    }
  
    private readonly global::System.Collections.Generic.List<network.pb_car_bet_item> _listSelf = new global::System.Collections.Generic.List<network.pb_car_bet_item>();
    [global::ProtoBuf.ProtoMember(3, Name=@"listSelf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_car_bet_item> listSelf
    {
      get { return _listSelf; }
    }
  
    private int _result;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _self_num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"self_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int self_num
    {
      get { return _self_num; }
      set { _self_num = value; }
    }
    private int _master_num;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"master_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int master_num
    {
      get { return _master_num; }
      set { _master_num = value; }
    }
    private int _pool_sub;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"pool_sub", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pool_sub
    {
      get { return _pool_sub; }
      set { _pool_sub = value; }
    }
    private int _pool;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"pool", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pool
    {
      get { return _pool; }
      set { _pool = value; }
    }

    private int _bet_limit = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"bet_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bet_limit
    {
      get { return _bet_limit; }
      set { _bet_limit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_hint_reply")]
  public partial class sc_car_hint_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_hint_reply() {}
    
    private byte[] _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_result_reply")]
  public partial class sc_car_result_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_result_reply() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _resultIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"resultIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resultIndex
    {
      get { return _resultIndex; }
      set { _resultIndex = value; }
    }
    private int _selfNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"selfNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int selfNum
    {
      get { return _selfNum; }
      set { _selfNum = value; }
    }
    private int _masterNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"masterNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int masterNum
    {
      get { return _masterNum; }
      set { _masterNum = value; }
    }
    private int _poolSub;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"poolSub", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int poolSub
    {
      get { return _poolSub; }
      set { _poolSub = value; }
    }
    private int _pool;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"pool", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pool
    {
      get { return _pool; }
      set { _pool = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_pool_reply")]
  public partial class sc_car_pool_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_pool_reply() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_car_add_money_req")]
  public partial class cs_car_add_money_req : global::ProtoBuf.IExtensible
  {
    public cs_car_add_money_req() {}
    
    private int _money;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_car_add_money_reply")]
  public partial class sc_car_add_money_reply : global::ProtoBuf.IExtensible
  {
    public sc_car_add_money_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_car_syn_in_game_state_req")]
  public partial class cs_car_syn_in_game_state_req : global::ProtoBuf.IExtensible
  {
    public cs_car_syn_in_game_state_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}