//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: chest.proto
// Note: requires additional types generated from: item.proto
namespace network
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_player_niu_room_chest_draw")]
  public partial class cs_player_niu_room_chest_draw : global::ProtoBuf.IExtensible
  {
    public cs_player_niu_room_chest_draw() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _game_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int game_type
    {
      get { return _game_type; }
      set { _game_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_room_chest_draw_reply")]
  public partial class sc_niu_room_chest_draw_reply : global::ProtoBuf.IExtensible
  {
    public sc_niu_room_chest_draw_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _rewards = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> rewards
    {
      get { return _rewards; }
    }
  
    private int _game_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"game_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int game_type
    {
      get { return _game_type; }
      set { _game_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_room_chest_info_update")]
  public partial class sc_niu_room_chest_info_update : global::ProtoBuf.IExtensible
  {
    public sc_niu_room_chest_info_update() {}
    
    private uint _times;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private int _game_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int game_type
    {
      get { return _game_type; }
      set { _game_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_room_chest_times_update")]
  public partial class sc_niu_room_chest_times_update : global::ProtoBuf.IExtensible
  {
    public sc_niu_room_chest_times_update() {}
    
    private uint _times_niu;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"times_niu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint times_niu
    {
      get { return _times_niu; }
      set { _times_niu = value; }
    }
    private uint _times_hundred;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"times_hundred", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint times_hundred
    {
      get { return _times_hundred; }
      set { _times_hundred = value; }
    }
    private uint _times_laba;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"times_laba", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint times_laba
    {
      get { return _times_laba; }
      set { _times_laba = value; }
    }
    private int _update_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"update_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int update_type
    {
      get { return _update_type; }
      set { _update_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}