//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Gift.proto
namespace Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CGiftRequest")]
  public partial class CS_CGiftRequest : global::ProtoBuf.IExtensible
  {
    public CS_CGiftRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CMonthRequest")]
  public partial class CS_CMonthRequest : global::ProtoBuf.IExtensible
  {
    public CS_CMonthRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CGiftInfoResponse")]
  public partial class SC_CGiftInfoResponse : global::ProtoBuf.IExtensible
  {
    public SC_CGiftInfoResponse() {}
    
    private int _giftStatus;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"giftStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int giftStatus
    {
      get { return _giftStatus; }
      set { _giftStatus = value; }
    }

    private int _monthStatus = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"monthStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monthStatus
    {
      get { return _monthStatus; }
      set { _monthStatus = value; }
    }

    private int _monthToday = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"monthToday", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monthToday
    {
      get { return _monthToday; }
      set { _monthToday = value; }
    }

    private int _remainDay = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"remainDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int remainDay
    {
      get { return _remainDay; }
      set { _remainDay = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}