//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Head.proto
namespace Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CHeadUseRequest")]
  public partial class CS_CHeadUseRequest : global::ProtoBuf.IExtensible
  {
    public CS_CHeadUseRequest() {}
    
    private int _headId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"headId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headId
    {
      get { return _headId; }
      set { _headId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CHeadFrameUseRequest")]
  public partial class CS_CHeadFrameUseRequest : global::ProtoBuf.IExtensible
  {
    public CS_CHeadFrameUseRequest() {}
    
    private int _headFrameId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"headFrameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headFrameId
    {
      get { return _headFrameId; }
      set { _headFrameId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CHeadBuyRequest")]
  public partial class CS_CHeadBuyRequest : global::ProtoBuf.IExtensible
  {
    public CS_CHeadBuyRequest() {}
    
    private int _headId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"headId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headId
    {
      get { return _headId; }
      set { _headId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CHeadFrameBuyRequest")]
  public partial class CS_CHeadFrameBuyRequest : global::ProtoBuf.IExtensible
  {
    public CS_CHeadFrameBuyRequest() {}
    
    private int _headFrameId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"headFrameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headFrameId
    {
      get { return _headFrameId; }
      set { _headFrameId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CHeadListResponse")]
  public partial class SC_CHeadListResponse : global::ProtoBuf.IExtensible
  {
    public SC_CHeadListResponse() {}
    
    private readonly global::System.Collections.Generic.List<int> _list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CHeadAddResponse")]
  public partial class SC_CHeadAddResponse : global::ProtoBuf.IExtensible
  {
    public SC_CHeadAddResponse() {}
    
    private readonly global::System.Collections.Generic.List<int> _list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CHeadUseResponse")]
  public partial class SC_CHeadUseResponse : global::ProtoBuf.IExtensible
  {
    public SC_CHeadUseResponse() {}
    
    private int _headId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"headId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headId
    {
      get { return _headId; }
      set { _headId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CHeadFrameListResponse")]
  public partial class SC_CHeadFrameListResponse : global::ProtoBuf.IExtensible
  {
    public SC_CHeadFrameListResponse() {}
    
    private readonly global::System.Collections.Generic.List<int> _list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CHeadFrameAddResponse")]
  public partial class SC_CHeadFrameAddResponse : global::ProtoBuf.IExtensible
  {
    public SC_CHeadFrameAddResponse() {}
    
    private readonly global::System.Collections.Generic.List<int> _list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CHeadFrameUseResponse")]
  public partial class SC_CHeadFrameUseResponse : global::ProtoBuf.IExtensible
  {
    public SC_CHeadFrameUseResponse() {}
    
    private int _headFrameId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"headFrameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headFrameId
    {
      get { return _headFrameId; }
      set { _headFrameId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}