//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: hundred_niu.proto
// Note: requires additional types generated from: niu_game.proto
namespace network
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_niu_room_state_update")]
  public partial class sc_hundred_niu_room_state_update : global::ProtoBuf.IExtensible
  {
    public sc_hundred_niu_room_state_update() {}
    
    private uint _state_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state_id
    {
      get { return _state_id; }
      set { _state_id = value; }
    }
    private uint _end_sec_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"end_sec_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint end_sec_time
    {
      get { return _end_sec_time; }
      set { _end_sec_time = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_one_player_poker_card> _last_card_info = new global::System.Collections.Generic.List<network.pb_one_player_poker_card>();
    [global::ProtoBuf.ProtoMember(3, Name=@"last_card_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_one_player_poker_card> last_card_info
    {
      get { return _last_card_info; }
    }
  
    private readonly global::System.Collections.Generic.List<network.hundred_game_over_settlement> _settle_list = new global::System.Collections.Generic.List<network.hundred_game_over_settlement>();
    [global::ProtoBuf.ProtoMember(4, Name=@"settle_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.hundred_game_over_settlement> settle_list
    {
      get { return _settle_list; }
    }
  

    private ulong _reward_pool_num = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"reward_pool_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong reward_pool_num
    {
      get { return _reward_pool_num; }
      set { _reward_pool_num = value; }
    }

    private network.pb_hundred_win_rec _last_win_rec = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"last_win_rec", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public network.pb_hundred_win_rec last_win_rec
    {
      get { return _last_win_rec; }
      set { _last_win_rec = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_pool_reward_info> _pool_reward = new global::System.Collections.Generic.List<network.pb_pool_reward_info>();
    [global::ProtoBuf.ProtoMember(7, Name=@"pool_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_pool_reward_info> pool_reward
    {
      get { return _pool_reward; }
    }
  

    private uint _master_continuous = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"master_continuous", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint master_continuous
    {
      get { return _master_continuous; }
      set { _master_continuous = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_pool_reward_info")]
  public partial class pb_pool_reward_info : global::ProtoBuf.IExtensible
  {
    public pb_pool_reward_info() {}
    
    private uint _set_pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"set_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint set_pos
    {
      get { return _set_pos; }
      set { _set_pos = value; }
    }
    private ulong _total_reward_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"total_reward_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong total_reward_num
    {
      get { return _total_reward_num; }
      set { _total_reward_num = value; }
    }
    private readonly global::System.Collections.Generic.List<network.hundred_game_over_settlement> _seat_reward_num = new global::System.Collections.Generic.List<network.hundred_game_over_settlement>();
    [global::ProtoBuf.ProtoMember(3, Name=@"seat_reward_num", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.hundred_game_over_settlement> seat_reward_num
    {
      get { return _seat_reward_num; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"hundred_game_over_settlement")]
  public partial class hundred_game_over_settlement : global::ProtoBuf.IExtensible
  {
    public hundred_game_over_settlement() {}
    
    private uint _player_pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player_pos
    {
      get { return _player_pos; }
      set { _player_pos = value; }
    }
    private long _reward_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reward_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long reward_num
    {
      get { return _reward_num; }
      set { _reward_num = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _set_pos_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"set_pos_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> set_pos_list
    {
      get { return _set_pos_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_one_player_poker_card")]
  public partial class pb_one_player_poker_card : global::ProtoBuf.IExtensible
  {
    public pb_one_player_poker_card() {}
    
    private uint _seat_pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat_pos
    {
      get { return _seat_pos; }
      set { _seat_pos = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_poker_card> _card_list = new global::System.Collections.Generic.List<network.pb_poker_card>();
    [global::ProtoBuf.ProtoMember(2, Name=@"card_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_poker_card> card_list
    {
      get { return _card_list; }
    }
  
    private uint _card_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint card_type
    {
      get { return _card_type; }
      set { _card_type = value; }
    }

    private bool _is_win = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"is_win", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_win
    {
      get { return _is_win; }
      set { _is_win = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_hundred_niu_enter_room_req")]
  public partial class cs_hundred_niu_enter_room_req : global::ProtoBuf.IExtensible
  {
    public cs_hundred_niu_enter_room_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_niu_enter_room_reply")]
  public partial class sc_hundred_niu_enter_room_reply : global::ProtoBuf.IExtensible
  {
    public sc_hundred_niu_enter_room_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }

    private network.pb_hundred_niu_room_data _game_data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"game_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public network.pb_hundred_niu_room_data game_data
    {
      get { return _game_data; }
      set { _game_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_hundred_niu_room_data")]
  public partial class pb_hundred_niu_room_data : global::ProtoBuf.IExtensible
  {
    public pb_hundred_niu_room_data() {}
    
    private uint _state_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state_id
    {
      get { return _state_id; }
      set { _state_id = value; }
    }
    private uint _end_sec_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"end_sec_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint end_sec_time
    {
      get { return _end_sec_time; }
      set { _end_sec_time = value; }
    }

    private ulong _reward_pool_num = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reward_pool_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong reward_pool_num
    {
      get { return _reward_pool_num; }
      set { _reward_pool_num = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_set_chips_info> _my_set_chips_info = new global::System.Collections.Generic.List<network.pb_set_chips_info>();
    [global::ProtoBuf.ProtoMember(4, Name=@"my_set_chips_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_set_chips_info> my_set_chips_info
    {
      get { return _my_set_chips_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_hundred_niu_player_list_query_req")]
  public partial class cs_hundred_niu_player_list_query_req : global::ProtoBuf.IExtensible
  {
    public cs_hundred_niu_player_list_query_req() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_niu_player_list_query_reply")]
  public partial class sc_hundred_niu_player_list_query_reply : global::ProtoBuf.IExtensible
  {
    public sc_hundred_niu_player_list_query_reply() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_hundred_niu_player_info> _list = new global::System.Collections.Generic.List<network.pb_hundred_niu_player_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_hundred_niu_player_info> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_hundred_niu_player_info")]
  public partial class pb_hundred_niu_player_info : global::ProtoBuf.IExtensible
  {
    public pb_hundred_niu_player_info() {}
    
    private string _player_uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_uuid
    {
      get { return _player_uuid; }
      set { _player_uuid = value; }
    }
    private uint _icon_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"icon_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint icon_type
    {
      get { return _icon_type; }
      set { _icon_type = value; }
    }

    private string _icon_url = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"icon_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon_url
    {
      get { return _icon_url; }
      set { _icon_url = value; }
    }

    private byte[] _player_name = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }
    private uint _vip_level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }

    private ulong _gold = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong gold
    {
      get { return _gold; }
      set { _gold = value; }
    }

    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }

    private ulong _pool_win_gold = default(ulong);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"pool_win_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong pool_win_gold
    {
      get { return _pool_win_gold; }
      set { _pool_win_gold = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_hundred_niu_free_set_chips_req")]
  public partial class cs_hundred_niu_free_set_chips_req : global::ProtoBuf.IExtensible
  {
    public cs_hundred_niu_free_set_chips_req() {}
    
    private uint _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private ulong _chips_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"chips_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong chips_num
    {
      get { return _chips_num; }
      set { _chips_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_niu_free_set_chips_reply")]
  public partial class sc_hundred_niu_free_set_chips_reply : global::ProtoBuf.IExtensible
  {
    public sc_hundred_niu_free_set_chips_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private uint _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private ulong _total_chips_num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"total_chips_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong total_chips_num
    {
      get { return _total_chips_num; }
      set { _total_chips_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_niu_free_set_chips_update")]
  public partial class sc_hundred_niu_free_set_chips_update : global::ProtoBuf.IExtensible
  {
    public sc_hundred_niu_free_set_chips_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_set_chips_info> _upd_list = new global::System.Collections.Generic.List<network.pb_set_chips_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"upd_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_set_chips_info> upd_list
    {
      get { return _upd_list; }
    }
  

    private uint _upd_flag = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"upd_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint upd_flag
    {
      get { return _upd_flag; }
      set { _upd_flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_set_chips_info")]
  public partial class pb_set_chips_info : global::ProtoBuf.IExtensible
  {
    public pb_set_chips_info() {}
    
    private uint _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private ulong _total_chips;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"total_chips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong total_chips
    {
      get { return _total_chips; }
      set { _total_chips = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_seat_set_info> _seat_pos_list = new global::System.Collections.Generic.List<network.pb_seat_set_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"seat_pos_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_seat_set_info> seat_pos_list
    {
      get { return _seat_pos_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_seat_set_info")]
  public partial class pb_seat_set_info : global::ProtoBuf.IExtensible
  {
    public pb_seat_set_info() {}
    
    private uint _seat_pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat_pos
    {
      get { return _seat_pos; }
      set { _seat_pos = value; }
    }
    private ulong _set_chips_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"set_chips_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong set_chips_num
    {
      get { return _set_chips_num; }
      set { _set_chips_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_hundred_niu_sit_down_req")]
  public partial class cs_hundred_niu_sit_down_req : global::ProtoBuf.IExtensible
  {
    public cs_hundred_niu_sit_down_req() {}
    
    private uint _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_niu_sit_down_reply")]
  public partial class sc_hundred_niu_sit_down_reply : global::ProtoBuf.IExtensible
  {
    public sc_hundred_niu_sit_down_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_niu_seat_player_info_update")]
  public partial class sc_hundred_niu_seat_player_info_update : global::ProtoBuf.IExtensible
  {
    public sc_hundred_niu_seat_player_info_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_hundred_niu_player_info> _seat_list = new global::System.Collections.Generic.List<network.pb_hundred_niu_player_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"seat_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_hundred_niu_player_info> seat_list
    {
      get { return _seat_list; }
    }
  

    private uint _delete_seat_pos = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"delete_seat_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint delete_seat_pos
    {
      get { return _delete_seat_pos; }
      set { _delete_seat_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_hundred_be_master_req")]
  public partial class cs_hundred_be_master_req : global::ProtoBuf.IExtensible
  {
    public cs_hundred_be_master_req() {}
    
    private uint _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private ulong _set_max;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"set_max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong set_max
    {
      get { return _set_max; }
      set { _set_max = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_be_master_reply")]
  public partial class sc_hundred_be_master_reply : global::ProtoBuf.IExtensible
  {
    public sc_hundred_be_master_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_hundred_query_master_list_req")]
  public partial class cs_hundred_query_master_list_req : global::ProtoBuf.IExtensible
  {
    public cs_hundred_query_master_list_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_query_master_list_reply")]
  public partial class sc_hundred_query_master_list_reply : global::ProtoBuf.IExtensible
  {
    public sc_hundred_query_master_list_reply() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_hundred_niu_player_info> _list = new global::System.Collections.Generic.List<network.pb_hundred_niu_player_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_hundred_niu_player_info> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_hundred_niu_in_game_syn_req")]
  public partial class cs_hundred_niu_in_game_syn_req : global::ProtoBuf.IExtensible
  {
    public cs_hundred_niu_in_game_syn_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_hundred_leave_room_req")]
  public partial class cs_hundred_leave_room_req : global::ProtoBuf.IExtensible
  {
    public cs_hundred_leave_room_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_leave_room_reply")]
  public partial class sc_hundred_leave_room_reply : global::ProtoBuf.IExtensible
  {
    public sc_hundred_leave_room_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_hundred_query_winning_rec_req")]
  public partial class cs_hundred_query_winning_rec_req : global::ProtoBuf.IExtensible
  {
    public cs_hundred_query_winning_rec_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_query_winning_rec_reply")]
  public partial class sc_hundred_query_winning_rec_reply : global::ProtoBuf.IExtensible
  {
    public sc_hundred_query_winning_rec_reply() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_hundred_win_rec> _list = new global::System.Collections.Generic.List<network.pb_hundred_win_rec>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_hundred_win_rec> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_hundred_win_rec")]
  public partial class pb_hundred_win_rec : global::ProtoBuf.IExtensible
  {
    public pb_hundred_win_rec() {}
    
    private bool _win_1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"win_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool win_1
    {
      get { return _win_1; }
      set { _win_1 = value; }
    }
    private bool _win_2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"win_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool win_2
    {
      get { return _win_2; }
      set { _win_2 = value; }
    }
    private bool _win_3;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"win_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool win_3
    {
      get { return _win_3; }
      set { _win_3 = value; }
    }
    private bool _win_4;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"win_4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool win_4
    {
      get { return _win_4; }
      set { _win_4 = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _pool_win = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"pool_win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> pool_win
    {
      get { return _pool_win; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_player_gold_change_update")]
  public partial class sc_hundred_player_gold_change_update : global::ProtoBuf.IExtensible
  {
    public sc_hundred_player_gold_change_update() {}
    
    private long _alter_num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"alter_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long alter_num
    {
      get { return _alter_num; }
      set { _alter_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_hundred_query_pool_win_player_req")]
  public partial class cs_hundred_query_pool_win_player_req : global::ProtoBuf.IExtensible
  {
    public cs_hundred_query_pool_win_player_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_query_pool_win_player_reply")]
  public partial class sc_hundred_query_pool_win_player_reply : global::ProtoBuf.IExtensible
  {
    public sc_hundred_query_pool_win_player_reply() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_hundred_niu_player_info> _list = new global::System.Collections.Generic.List<network.pb_hundred_niu_player_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_hundred_niu_player_info> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}