//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: item.proto
namespace network
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_items_update")]
  public partial class sc_items_update : global::ProtoBuf.IExtensible
  {
    public sc_items_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_item_info> _upd_list = new global::System.Collections.Generic.List<network.pb_item_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"upd_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_item_info> upd_list
    {
      get { return _upd_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_items_add")]
  public partial class sc_items_add : global::ProtoBuf.IExtensible
  {
    public sc_items_add() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_item_info> _add_list = new global::System.Collections.Generic.List<network.pb_item_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"add_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_item_info> add_list
    {
      get { return _add_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_items_delete")]
  public partial class sc_items_delete : global::ProtoBuf.IExtensible
  {
    public sc_items_delete() {}
    
    private readonly global::System.Collections.Generic.List<string> _del_list = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"del_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> del_list
    {
      get { return _del_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_items_init_update")]
  public partial class sc_items_init_update : global::ProtoBuf.IExtensible
  {
    public sc_items_init_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_item_info> _all_list = new global::System.Collections.Generic.List<network.pb_item_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"all_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_item_info> all_list
    {
      get { return _all_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_item_info")]
  public partial class pb_item_info : global::ProtoBuf.IExtensible
  {
    public pb_item_info() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _base_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"base_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint base_id
    {
      get { return _base_id; }
      set { _base_id = value; }
    }
    private uint _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_item_use_req")]
  public partial class cs_item_use_req : global::ProtoBuf.IExtensible
  {
    public cs_item_use_req() {}
    
    private string _item_uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"item_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string item_uuid
    {
      get { return _item_uuid; }
      set { _item_uuid = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_item_use_reply")]
  public partial class sc_item_use_reply : global::ProtoBuf.IExtensible
  {
    public sc_item_use_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private byte[] _err_msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"err_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] err_msg
    {
      get { return _err_msg; }
      set { _err_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_reward_info")]
  public partial class pb_reward_info : global::ProtoBuf.IExtensible
  {
    public pb_reward_info() {}
    
    private uint _base_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"base_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint base_id
    {
      get { return _base_id; }
      set { _base_id = value; }
    }
    private ulong _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}