//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
namespace network
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_login")]
  public partial class cs_login : global::ProtoBuf.IExtensible
  {
    public cs_login() {}
    
    private uint _platform_flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"platform_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint platform_flag
    {
      get { return _platform_flag; }
      set { _platform_flag = value; }
    }
    private string _uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private byte[] _password;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _sz_param;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sz_param", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sz_param
    {
      get { return _sz_param; }
      set { _sz_param = value; }
    }
    private string _version;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _network_type;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"network_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string network_type
    {
      get { return _network_type; }
      set { _network_type = value; }
    }
    private uint _sys_type;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"sys_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sys_type
    {
      get { return _sys_type; }
      set { _sys_type = value; }
    }
    private uint _chnid;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"chnid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint chnid
    {
      get { return _chnid; }
      set { _chnid = value; }
    }
    private uint _sub_chnid;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"sub_chnid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sub_chnid
    {
      get { return _sub_chnid; }
      set { _sub_chnid = value; }
    }
    private string _ios_idfa;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"ios_idfa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ios_idfa
    {
      get { return _ios_idfa; }
      set { _ios_idfa = value; }
    }
    private string _ios_idfv;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"ios_idfv", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ios_idfv
    {
      get { return _ios_idfv; }
      set { _ios_idfv = value; }
    }
    private string _mac_address;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"mac_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mac_address
    {
      get { return _mac_address; }
      set { _mac_address = value; }
    }
    private string _device_type;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"device_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device_type
    {
      get { return _device_type; }
      set { _device_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_login_reply")]
  public partial class sc_login_reply : global::ProtoBuf.IExtensible
  {
    public sc_login_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private byte[] _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private string _reconnect_key;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"reconnect_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string reconnect_key
    {
      get { return _reconnect_key; }
      set { _reconnect_key = value; }
    }
    private byte[] _proto_key;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"proto_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] proto_key
    {
      get { return _proto_key; }
      set { _proto_key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_login_out")]
  public partial class cs_login_out : global::ProtoBuf.IExtensible
  {
    public cs_login_out() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_login_reconnection")]
  public partial class cs_login_reconnection : global::ProtoBuf.IExtensible
  {
    public cs_login_reconnection() {}
    
    private uint _platform_flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"platform_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint platform_flag
    {
      get { return _platform_flag; }
      set { _platform_flag = value; }
    }
    private string _user;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user
    {
      get { return _user; }
      set { _user = value; }
    }
    private string _reconnect_key;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"reconnect_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string reconnect_key
    {
      get { return _reconnect_key; }
      set { _reconnect_key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_login_reconnection_reply")]
  public partial class sc_login_reconnection_reply : global::ProtoBuf.IExtensible
  {
    public sc_login_reconnection_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private byte[] _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private byte[] _proto_key;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"proto_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] proto_key
    {
      get { return _proto_key; }
      set { _proto_key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_login_repeat")]
  public partial class sc_login_repeat : global::ProtoBuf.IExtensible
  {
    public sc_login_repeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_login_proto_complete")]
  public partial class sc_login_proto_complete : global::ProtoBuf.IExtensible
  {
    public sc_login_proto_complete() {}
    
    private bool _is_new_player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_new_player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_new_player
    {
      get { return _is_new_player; }
      set { _is_new_player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}