//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mail.proto
// Note: requires additional types generated from: item.proto
namespace network
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_mails_init_update")]
  public partial class sc_mails_init_update : global::ProtoBuf.IExtensible
  {
    public sc_mails_init_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_mail> _sys_mails = new global::System.Collections.Generic.List<network.pb_mail>();
    [global::ProtoBuf.ProtoMember(1, Name=@"sys_mails", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_mail> sys_mails
    {
      get { return _sys_mails; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_mail")]
  public partial class pb_mail : global::ProtoBuf.IExtensible
  {
    public pb_mail() {}
    
    private string _mail_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
    private uint _cls;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cls", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cls
    {
      get { return _cls; }
      set { _cls = value; }
    }
    private byte[] _title;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] title
    {
      get { return _title; }
      set { _title = value; }
    }
    private byte[] _content;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] content
    {
      get { return _content; }
      set { _content = value; }
    }
    private bool _read;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"read", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool read
    {
      get { return _read; }
      set { _read = value; }
    }
    private uint _receive_date;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"receive_date", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint receive_date
    {
      get { return _receive_date; }
      set { _receive_date = value; }
    }
    private uint _expire_date;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"expire_date", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint expire_date
    {
      get { return _expire_date; }
      set { _expire_date = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _reward_list = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(8, Name=@"reward_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> reward_list
    {
      get { return _reward_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_mail_add")]
  public partial class sc_mail_add : global::ProtoBuf.IExtensible
  {
    public sc_mail_add() {}
    
    private network.pb_mail _add_sys_mail;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"add_sys_mail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public network.pb_mail add_sys_mail
    {
      get { return _add_sys_mail; }
      set { _add_sys_mail = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_mail_delete_request")]
  public partial class cs_mail_delete_request : global::ProtoBuf.IExtensible
  {
    public cs_mail_delete_request() {}
    
    private string _mail_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }

    private string _request_mark = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"request_mark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string request_mark
    {
      get { return _request_mark; }
      set { _request_mark = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_mail_delete_reply")]
  public partial class sc_mail_delete_reply : global::ProtoBuf.IExtensible
  {
    public sc_mail_delete_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err_msg = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err_msg
    {
      get { return _err_msg; }
      set { _err_msg = value; }
    }

    private string _request_mark = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"request_mark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string request_mark
    {
      get { return _request_mark; }
      set { _request_mark = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_read_mail")]
  public partial class cs_read_mail : global::ProtoBuf.IExtensible
  {
    public cs_read_mail() {}
    
    private string _mail_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_mail_draw_request")]
  public partial class cs_mail_draw_request : global::ProtoBuf.IExtensible
  {
    public cs_mail_draw_request() {}
    
    private readonly global::System.Collections.Generic.List<string> _mail_ids = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mail_ids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> mail_ids
    {
      get { return _mail_ids; }
    }
  

    private string _request_mark = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"request_mark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string request_mark
    {
      get { return _request_mark; }
      set { _request_mark = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_mail_draw_reply")]
  public partial class sc_mail_draw_reply : global::ProtoBuf.IExtensible
  {
    public sc_mail_draw_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err_msg = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err_msg
    {
      get { return _err_msg; }
      set { _err_msg = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _reward_info_s = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"reward_info_s", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> reward_info_s
    {
      get { return _reward_info_s; }
    }
  

    private string _request_mark = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"request_mark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string request_mark
    {
      get { return _request_mark; }
      set { _request_mark = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}