//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: niu_game.proto
// Note: requires additional types generated from: item.proto
namespace network
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_room_state_update")]
  public partial class sc_niu_room_state_update : global::ProtoBuf.IExtensible
  {
    public sc_niu_room_state_update() {}
    
    private uint _state_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state_id
    {
      get { return _state_id; }
      set { _state_id = value; }
    }
    private uint _end_sec_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"end_sec_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint end_sec_time
    {
      get { return _end_sec_time; }
      set { _end_sec_time = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_poker_card> _open_card_list = new global::System.Collections.Generic.List<network.pb_poker_card>();
    [global::ProtoBuf.ProtoMember(3, Name=@"open_card_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_poker_card> open_card_list
    {
      get { return _open_card_list; }
    }
  

    private uint _master_pos = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"master_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint master_pos
    {
      get { return _master_pos; }
      set { _master_pos = value; }
    }

    private network.pb_poker_card _last_card_info = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"last_card_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public network.pb_poker_card last_card_info
    {
      get { return _last_card_info; }
      set { _last_card_info = value; }
    }

    private network.game_over_settlement _settle_list = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"settle_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public network.game_over_settlement settle_list
    {
      get { return _settle_list; }
      set { _settle_list = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_niu_enter_room_req")]
  public partial class cs_niu_enter_room_req : global::ProtoBuf.IExtensible
  {
    public cs_niu_enter_room_req() {}
    
    private uint _room_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_type
    {
      get { return _room_type; }
      set { _room_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_enter_room_reply")]
  public partial class sc_niu_enter_room_reply : global::ProtoBuf.IExtensible
  {
    public sc_niu_enter_room_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _my_pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"my_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint my_pos
    {
      get { return _my_pos; }
      set { _my_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_enter_room_player_info_update")]
  public partial class sc_niu_enter_room_player_info_update : global::ProtoBuf.IExtensible
  {
    public sc_niu_enter_room_player_info_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_niu_player_info> _player_list = new global::System.Collections.Generic.List<network.pb_niu_player_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_niu_player_info> player_list
    {
      get { return _player_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_niu_choose_master_rate_req")]
  public partial class cs_niu_choose_master_rate_req : global::ProtoBuf.IExtensible
  {
    public cs_niu_choose_master_rate_req() {}
    
    private uint _rate_num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rate_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rate_num
    {
      get { return _rate_num; }
      set { _rate_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_choose_master_rate_reply")]
  public partial class sc_niu_choose_master_rate_reply : global::ProtoBuf.IExtensible
  {
    public sc_niu_choose_master_rate_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_player_choose_master_rate_update")]
  public partial class sc_niu_player_choose_master_rate_update : global::ProtoBuf.IExtensible
  {
    public sc_niu_player_choose_master_rate_update() {}
    
    private uint _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _rate_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rate_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rate_num
    {
      get { return _rate_num; }
      set { _rate_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_niu_choose_free_rate_req")]
  public partial class cs_niu_choose_free_rate_req : global::ProtoBuf.IExtensible
  {
    public cs_niu_choose_free_rate_req() {}
    
    private uint _rate_num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rate_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rate_num
    {
      get { return _rate_num; }
      set { _rate_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_choose_free_rate_reply")]
  public partial class sc_niu_choose_free_rate_reply : global::ProtoBuf.IExtensible
  {
    public sc_niu_choose_free_rate_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_player_choose_free_rate_update")]
  public partial class sc_niu_player_choose_free_rate_update : global::ProtoBuf.IExtensible
  {
    public sc_niu_player_choose_free_rate_update() {}
    
    private uint _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _rate_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rate_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rate_num
    {
      get { return _rate_num; }
      set { _rate_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_niu_leave_room_req")]
  public partial class cs_niu_leave_room_req : global::ProtoBuf.IExtensible
  {
    public cs_niu_leave_room_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_leave_room_reply")]
  public partial class sc_niu_leave_room_reply : global::ProtoBuf.IExtensible
  {
    public sc_niu_leave_room_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_leave_room_player_pos_update")]
  public partial class sc_niu_leave_room_player_pos_update : global::ProtoBuf.IExtensible
  {
    public sc_niu_leave_room_player_pos_update() {}
    
    private uint _leave_pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"leave_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint leave_pos
    {
      get { return _leave_pos; }
      set { _leave_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_niu_submit_card_req")]
  public partial class cs_niu_submit_card_req : global::ProtoBuf.IExtensible
  {
    public cs_niu_submit_card_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_submit_card_reply")]
  public partial class sc_niu_submit_card_reply : global::ProtoBuf.IExtensible
  {
    public sc_niu_submit_card_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_player_submit_card_update")]
  public partial class sc_niu_player_submit_card_update : global::ProtoBuf.IExtensible
  {
    public sc_niu_player_submit_card_update() {}
    
    private uint _player_pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player_pos
    {
      get { return _player_pos; }
      set { _player_pos = value; }
    }
    private uint _card_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint card_type
    {
      get { return _card_type; }
      set { _card_type = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_poker_card> _card_list = new global::System.Collections.Generic.List<network.pb_poker_card>();
    [global::ProtoBuf.ProtoMember(3, Name=@"card_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_poker_card> card_list
    {
      get { return _card_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_niu_syn_in_game_state_req")]
  public partial class cs_niu_syn_in_game_state_req : global::ProtoBuf.IExtensible
  {
    public cs_niu_syn_in_game_state_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_niu_query_player_room_info_req")]
  public partial class cs_niu_query_player_room_info_req : global::ProtoBuf.IExtensible
  {
    public cs_niu_query_player_room_info_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_player_room_info_update")]
  public partial class sc_niu_player_room_info_update : global::ProtoBuf.IExtensible
  {
    public sc_niu_player_room_info_update() {}
    
    private uint _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private uint _enter_end_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"enter_end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint enter_end_time
    {
      get { return _enter_end_time; }
      set { _enter_end_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_player_back_to_room_info_update")]
  public partial class sc_niu_player_back_to_room_info_update : global::ProtoBuf.IExtensible
  {
    public sc_niu_player_back_to_room_info_update() {}
    
    private uint _state_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state_id
    {
      get { return _state_id; }
      set { _state_id = value; }
    }
    private uint _end_sec_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"end_sec_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint end_sec_time
    {
      get { return _end_sec_time; }
      set { _end_sec_time = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_niu_player_info> _player_list = new global::System.Collections.Generic.List<network.pb_niu_player_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"player_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_niu_player_info> player_list
    {
      get { return _player_list; }
    }
  

    private uint _master_pos = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"master_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint master_pos
    {
      get { return _master_pos; }
      set { _master_pos = value; }
    }
    private uint _my_pos;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"my_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint my_pos
    {
      get { return _my_pos; }
      set { _my_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_poker_card")]
  public partial class pb_poker_card : global::ProtoBuf.IExtensible
  {
    public pb_poker_card() {}
    
    private uint _number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint number
    {
      get { return _number; }
      set { _number = value; }
    }
    private uint _color;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint color
    {
      get { return _color; }
      set { _color = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"game_over_settlement")]
  public partial class game_over_settlement : global::ProtoBuf.IExtensible
  {
    public game_over_settlement() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_settle_info> _all_player_settle_info = new global::System.Collections.Generic.List<network.pb_settle_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"all_player_settle_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_settle_info> all_player_settle_info
    {
      get { return _all_player_settle_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_settle_info")]
  public partial class pb_settle_info : global::ProtoBuf.IExtensible
  {
    public pb_settle_info() {}
    
    private uint _player_pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player_pos
    {
      get { return _player_pos; }
      set { _player_pos = value; }
    }
    private long _reward_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reward_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long reward_num
    {
      get { return _reward_num; }
      set { _reward_num = value; }
    }
    private uint _card_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint card_type
    {
      get { return _card_type; }
      set { _card_type = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_poker_card> _card_list = new global::System.Collections.Generic.List<network.pb_poker_card>();
    [global::ProtoBuf.ProtoMember(4, Name=@"card_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_poker_card> card_list
    {
      get { return _card_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_niu_player_info")]
  public partial class pb_niu_player_info : global::ProtoBuf.IExtensible
  {
    public pb_niu_player_info() {}
    
    private uint _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private string _player_uuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_uuid
    {
      get { return _player_uuid; }
      set { _player_uuid = value; }
    }
    private ulong _gold_num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gold_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong gold_num
    {
      get { return _gold_num; }
      set { _gold_num = value; }
    }
    private uint _icon_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"icon_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint icon_type
    {
      get { return _icon_type; }
      set { _icon_type = value; }
    }

    private string _icon_url = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"icon_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon_url
    {
      get { return _icon_url; }
      set { _icon_url = value; }
    }

    private byte[] _player_name = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }

    private uint _master_rate = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"master_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint master_rate
    {
      get { return _master_rate; }
      set { _master_rate = value; }
    }

    private uint _free_rate = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"free_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint free_rate
    {
      get { return _free_rate; }
      set { _free_rate = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_poker_card> _open_card_list = new global::System.Collections.Generic.List<network.pb_poker_card>();
    [global::ProtoBuf.ProtoMember(9, Name=@"open_card_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_poker_card> open_card_list
    {
      get { return _open_card_list; }
    }
  

    private uint _card_type = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"card_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint card_type
    {
      get { return _card_type; }
      set { _card_type = value; }
    }
    private uint _vip_level;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_redpack_room_reset_times_update")]
  public partial class sc_redpack_room_reset_times_update : global::ProtoBuf.IExtensible
  {
    public sc_redpack_room_reset_times_update() {}
    
    private uint _left_reset_times;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"left_reset_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint left_reset_times
    {
      get { return _left_reset_times; }
      set { _left_reset_times = value; }
    }
    private uint _reset_seconds;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reset_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reset_seconds
    {
      get { return _reset_seconds; }
      set { _reset_seconds = value; }
    }
    private uint _reset_mission_is_draw;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"reset_mission_is_draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reset_mission_is_draw
    {
      get { return _reset_mission_is_draw; }
      set { _reset_mission_is_draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_redpack_room_player_times_update")]
  public partial class sc_redpack_room_player_times_update : global::ProtoBuf.IExtensible
  {
    public sc_redpack_room_player_times_update() {}
    
    private uint _now_play_times;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"now_play_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint now_play_times
    {
      get { return _now_play_times; }
      set { _now_play_times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_redpack_room_redpack_notice_update")]
  public partial class sc_redpack_room_redpack_notice_update : global::ProtoBuf.IExtensible
  {
    public sc_redpack_room_redpack_notice_update() {}
    
    private uint _close_draw_second;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"close_draw_second", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint close_draw_second
    {
      get { return _close_draw_second; }
      set { _close_draw_second = value; }
    }
    private uint _next_open_redpack_second;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"next_open_redpack_second", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint next_open_redpack_second
    {
      get { return _next_open_redpack_second; }
      set { _next_open_redpack_second = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_redpack_room_draw_req")]
  public partial class cs_redpack_room_draw_req : global::ProtoBuf.IExtensible
  {
    public cs_redpack_room_draw_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_redpack_room_draw_reply")]
  public partial class sc_redpack_room_draw_reply : global::ProtoBuf.IExtensible
  {
    public sc_redpack_room_draw_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private byte[] _err;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _reward = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> reward
    {
      get { return _reward; }
    }
  
    private uint _next_can_draw_second;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"next_can_draw_second", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint next_can_draw_second
    {
      get { return _next_can_draw_second; }
      set { _next_can_draw_second = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_redpack_redpack_timer_sec_update")]
  public partial class sc_redpack_redpack_timer_sec_update : global::ProtoBuf.IExtensible
  {
    public sc_redpack_redpack_timer_sec_update() {}
    
    private uint _next_can_draw_second;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"next_can_draw_second", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint next_can_draw_second
    {
      get { return _next_can_draw_second; }
      set { _next_can_draw_second = value; }
    }
    private uint _next_open_redpack_second;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"next_open_redpack_second", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint next_open_redpack_second
    {
      get { return _next_open_redpack_second; }
      set { _next_open_redpack_second = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_redpack_relive_req")]
  public partial class cs_redpack_relive_req : global::ProtoBuf.IExtensible
  {
    public cs_redpack_relive_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_redpack_relive_reply")]
  public partial class sc_redpack_relive_reply : global::ProtoBuf.IExtensible
  {
    public sc_redpack_relive_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private byte[] _err;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_redpack_relive_times")]
  public partial class sc_redpack_relive_times : global::ProtoBuf.IExtensible
  {
    public sc_redpack_relive_times() {}
    
    private uint _times;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_fudai_pool_update")]
  public partial class sc_fudai_pool_update : global::ProtoBuf.IExtensible
  {
    public sc_fudai_pool_update() {}
    
    private int _num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}