//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Online.proto
namespace Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_COnlineAwardRequest")]
  public partial class CS_COnlineAwardRequest : global::ProtoBuf.IExtensible
  {
    public CS_COnlineAwardRequest() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_COnlineIntervalAwardRequest")]
  public partial class CS_COnlineIntervalAwardRequest : global::ProtoBuf.IExtensible
  {
    public CS_COnlineIntervalAwardRequest() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_COnlineAwardAllRequest")]
  public partial class CS_COnlineAwardAllRequest : global::ProtoBuf.IExtensible
  {
    public CS_COnlineAwardAllRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_COnlineNewbieAwardRequest")]
  public partial class CS_COnlineNewbieAwardRequest : global::ProtoBuf.IExtensible
  {
    public CS_COnlineNewbieAwardRequest() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_COnlineResponse")]
  public partial class SC_COnlineResponse : global::ProtoBuf.IExtensible
  {
    public SC_COnlineResponse() {}
    
    private int _accTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int accTime
    {
      get { return _accTime; }
      set { _accTime = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _status = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> status
    {
      get { return _status; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _statusInterval = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"statusInterval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> statusInterval
    {
      get { return _statusInterval; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_COnlineNewbieResponse")]
  public partial class SC_COnlineNewbieResponse : global::ProtoBuf.IExtensible
  {
    public SC_COnlineNewbieResponse() {}
    
    private int _accTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int accTime
    {
      get { return _accTime; }
      set { _accTime = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _status = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> status
    {
      get { return _status; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}