//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: player.proto
// Note: requires additional types generated from: item.proto
namespace network
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_player_base_info")]
  public partial class sc_player_base_info : global::ProtoBuf.IExtensible
  {
    public sc_player_base_info() {}
    
    private string _player_uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_uuid
    {
      get { return _player_uuid; }
      set { _player_uuid = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private ulong _gold;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private uint _diamond;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private uint _cash;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"cash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cash
    {
      get { return _cash; }
      set { _cash = value; }
    }
    private uint _exp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _icon;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _vip_level;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }
    private uint _rmb;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"rmb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rmb
    {
      get { return _rmb; }
      set { _rmb = value; }
    }
    private int _block;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"block", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int block
    {
      get { return _block; }
      set { _block = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_player_change_name_req")]
  public partial class cs_player_change_name_req : global::ProtoBuf.IExtensible
  {
    public cs_player_change_name_req() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_player_change_name_reply")]
  public partial class sc_player_change_name_reply : global::ProtoBuf.IExtensible
  {
    public sc_player_change_name_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_player_change_headicon_req")]
  public partial class cs_player_change_headicon_req : global::ProtoBuf.IExtensible
  {
    public cs_player_change_headicon_req() {}
    
    private string _icon;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_player_change_headicon_reply")]
  public partial class sc_player_change_headicon_reply : global::ProtoBuf.IExtensible
  {
    public sc_player_change_headicon_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_player_chat")]
  public partial class cs_player_chat : global::ProtoBuf.IExtensible
  {
    public cs_player_chat() {}
    
    private uint _room_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_type
    {
      get { return _room_type; }
      set { _room_type = value; }
    }
    private uint _content_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"content_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint content_type
    {
      get { return _content_type; }
      set { _content_type = value; }
    }
    private byte[] _content;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] content
    {
      get { return _content; }
      set { _content = value; }
    }
    private string _obj_player_uuid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"obj_player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string obj_player_uuid
    {
      get { return _obj_player_uuid; }
      set { _obj_player_uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_player_chat")]
  public partial class sc_player_chat : global::ProtoBuf.IExtensible
  {
    public sc_player_chat() {}
    
    private uint _room_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_type
    {
      get { return _room_type; }
      set { _room_type = value; }
    }
    private uint _content_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"content_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint content_type
    {
      get { return _content_type; }
      set { _content_type = value; }
    }
    private byte[] _content;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] content
    {
      get { return _content; }
      set { _content = value; }
    }
    private string _player_uuid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_uuid
    {
      get { return _player_uuid; }
      set { _player_uuid = value; }
    }
    private byte[] _player_name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }
    private byte[] _player_icon;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"player_icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] player_icon
    {
      get { return _player_icon; }
      set { _player_icon = value; }
    }
    private uint _player_vip;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"player_vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player_vip
    {
      get { return _player_vip; }
      set { _player_vip = value; }
    }
    private uint _player_seat_pos;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"player_seat_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player_seat_pos
    {
      get { return _player_seat_pos; }
      set { _player_seat_pos = value; }
    }
    private uint _send_time;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"send_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint send_time
    {
      get { return _send_time; }
      set { _send_time = value; }
    }

    private string _des_player_uuid = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"des_player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string des_player_uuid
    {
      get { return _des_player_uuid; }
      set { _des_player_uuid = value; }
    }

    private byte[] _des_player_name = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"des_player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] des_player_name
    {
      get { return _des_player_name; }
      set { _des_player_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_player_sys_notice")]
  public partial class sc_player_sys_notice : global::ProtoBuf.IExtensible
  {
    public sc_player_sys_notice() {}
    
    private uint _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private byte[] _content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_tips")]
  public partial class sc_tips : global::ProtoBuf.IExtensible
  {
    public sc_tips() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _text;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_query_player_winning_rec_req")]
  public partial class cs_query_player_winning_rec_req : global::ProtoBuf.IExtensible
  {
    public cs_query_player_winning_rec_req() {}
    

    private string _obj_player_uuid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"obj_player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string obj_player_uuid
    {
      get { return _obj_player_uuid; }
      set { _obj_player_uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_query_player_winning_rec_reply")]
  public partial class sc_query_player_winning_rec_reply : global::ProtoBuf.IExtensible
  {
    public sc_query_player_winning_rec_reply() {}
    
    private uint _win_rate;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"win_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint win_rate
    {
      get { return _win_rate; }
      set { _win_rate = value; }
    }
    private uint _win_count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"win_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint win_count
    {
      get { return _win_count; }
      set { _win_count = value; }
    }
    private uint _defeated_count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"defeated_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint defeated_count
    {
      get { return _defeated_count; }
      set { _defeated_count = value; }
    }
    private long _max_property;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"max_property", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long max_property
    {
      get { return _max_property; }
      set { _max_property = value; }
    }
    private long _total_profit;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"total_profit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long total_profit
    {
      get { return _total_profit; }
      set { _total_profit = value; }
    }
    private long _week_profit;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"week_profit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long week_profit
    {
      get { return _week_profit; }
      set { _week_profit = value; }
    }
    private uint _niu_10;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"niu_10", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint niu_10
    {
      get { return _niu_10; }
      set { _niu_10 = value; }
    }
    private uint _niu_11;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"niu_11", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint niu_11
    {
      get { return _niu_11; }
      set { _niu_11 = value; }
    }
    private uint _niu_12;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"niu_12", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint niu_12
    {
      get { return _niu_12; }
      set { _niu_12 = value; }
    }
    private uint _niu_13;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"niu_13", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint niu_13
    {
      get { return _niu_13; }
      set { _niu_13 = value; }
    }
    private uint _niu_0_win;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"niu_0_win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint niu_0_win
    {
      get { return _niu_0_win; }
      set { _niu_0_win = value; }
    }

    private string _obj_player_uuid = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"obj_player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string obj_player_uuid
    {
      get { return _obj_player_uuid; }
      set { _obj_player_uuid = value; }
    }

    private byte[] _obj_name = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"obj_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] obj_name
    {
      get { return _obj_name; }
      set { _obj_name = value; }
    }

    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }

    private ulong _gold = default(ulong);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong gold
    {
      get { return _gold; }
      set { _gold = value; }
    }

    private string _icon = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }

    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }

    private uint _vip_level = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }

    private string _account = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_niu_query_in_game_player_num_req")]
  public partial class cs_niu_query_in_game_player_num_req : global::ProtoBuf.IExtensible
  {
    public cs_niu_query_in_game_player_num_req() {}
    
    private uint _game_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_type
    {
      get { return _game_type; }
      set { _game_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_room_player_num")]
  public partial class pb_room_player_num : global::ProtoBuf.IExtensible
  {
    public pb_room_player_num() {}
    
    private uint _room_level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_level
    {
      get { return _room_level; }
      set { _room_level = value; }
    }
    private uint _player_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player_num
    {
      get { return _player_num; }
      set { _player_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_query_in_game_player_num_reply")]
  public partial class sc_niu_query_in_game_player_num_reply : global::ProtoBuf.IExtensible
  {
    public sc_niu_query_in_game_player_num_reply() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_room_player_num> _list = new global::System.Collections.Generic.List<network.pb_room_player_num>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_room_player_num> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_niu_subsidy_req")]
  public partial class cs_niu_subsidy_req : global::ProtoBuf.IExtensible
  {
    public cs_niu_subsidy_req() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_subsidy_reply")]
  public partial class sc_niu_subsidy_reply : global::ProtoBuf.IExtensible
  {
    public sc_niu_subsidy_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_subsidy_info_update")]
  public partial class sc_niu_subsidy_info_update : global::ProtoBuf.IExtensible
  {
    public sc_niu_subsidy_info_update() {}
    
    private uint _left_times;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"left_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint left_times
    {
      get { return _left_times; }
      set { _left_times = value; }
    }
    private uint _subsidy_gold;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"subsidy_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint subsidy_gold
    {
      get { return _subsidy_gold; }
      set { _subsidy_gold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_niu_special_subsidy_share")]
  public partial class cs_niu_special_subsidy_share : global::ProtoBuf.IExtensible
  {
    public cs_niu_special_subsidy_share() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_special_subsidy_share")]
  public partial class sc_niu_special_subsidy_share : global::ProtoBuf.IExtensible
  {
    public sc_niu_special_subsidy_share() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_player_base_make_name")]
  public partial class cs_player_base_make_name : global::ProtoBuf.IExtensible
  {
    public cs_player_base_make_name() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_player_base_make_name_back")]
  public partial class sc_player_base_make_name_back : global::ProtoBuf.IExtensible
  {
    public sc_player_base_make_name_back() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_daily_checkin_req")]
  public partial class cs_daily_checkin_req : global::ProtoBuf.IExtensible
  {
    public cs_daily_checkin_req() {}
    
    private uint _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_daily_checkin_reply")]
  public partial class sc_daily_checkin_reply : global::ProtoBuf.IExtensible
  {
    public sc_daily_checkin_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _rewards = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> rewards
    {
      get { return _rewards; }
    }
  
    private uint _flag;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_daily_checkin_info_update")]
  public partial class sc_daily_checkin_info_update : global::ProtoBuf.IExtensible
  {
    public sc_daily_checkin_info_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_checkin_info> _list = new global::System.Collections.Generic.List<network.pb_checkin_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_checkin_info> list
    {
      get { return _list; }
    }
  
    private uint _all_checkin_day;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"all_checkin_day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint all_checkin_day
    {
      get { return _all_checkin_day; }
      set { _all_checkin_day = value; }
    }
    private bool _is_checkin_today;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"is_checkin_today", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_checkin_today
    {
      get { return _is_checkin_today; }
      set { _is_checkin_today = value; }
    }
    private bool _vip_is_draw;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"vip_is_draw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool vip_is_draw
    {
      get { return _vip_is_draw; }
      set { _vip_is_draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_checkin_info")]
  public partial class pb_checkin_info : global::ProtoBuf.IExtensible
  {
    public pb_checkin_info() {}
    
    private uint _day;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint day
    {
      get { return _day; }
      set { _day = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _rewards = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> rewards
    {
      get { return _rewards; }
    }
  
    private bool _is_draw;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"is_draw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_draw
    {
      get { return _is_draw; }
      set { _is_draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_make_up_for_checkin_req")]
  public partial class cs_make_up_for_checkin_req : global::ProtoBuf.IExtensible
  {
    public cs_make_up_for_checkin_req() {}
    
    private uint _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_player_phone_num_info_update")]
  public partial class sc_player_phone_num_info_update : global::ProtoBuf.IExtensible
  {
    public sc_player_phone_num_info_update() {}
    
    private string _phone_num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"phone_num", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string phone_num
    {
      get { return _phone_num; }
      set { _phone_num = value; }
    }
    private bool _is_draw;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_draw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_draw
    {
      get { return _is_draw; }
      set { _is_draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_player_bind_phone_num")]
  public partial class sc_player_bind_phone_num : global::ProtoBuf.IExtensible
  {
    public sc_player_bind_phone_num() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_player_bind_phone_num_draw")]
  public partial class cs_player_bind_phone_num_draw : global::ProtoBuf.IExtensible
  {
    public cs_player_bind_phone_num_draw() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_player_bind_phone_num_draw_reply")]
  public partial class sc_player_bind_phone_num_draw_reply : global::ProtoBuf.IExtensible
  {
    public sc_player_bind_phone_num_draw_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _rewards = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> rewards
    {
      get { return _rewards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_niu_special_subsidy_info_update")]
  public partial class sc_niu_special_subsidy_info_update : global::ProtoBuf.IExtensible
  {
    public sc_niu_special_subsidy_info_update() {}
    
    private uint _left_times;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"left_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint left_times
    {
      get { return _left_times; }
      set { _left_times = value; }
    }
    private uint _subsidy_gold;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"subsidy_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint subsidy_gold
    {
      get { return _subsidy_gold; }
      set { _subsidy_gold = value; }
    }
    private bool _is_share;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"is_share", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_share
    {
      get { return _is_share; }
      set { _is_share = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_rank_query_req")]
  public partial class cs_rank_query_req : global::ProtoBuf.IExtensible
  {
    public cs_rank_query_req() {}
    
    private uint _rank_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rank_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank_type
    {
      get { return _rank_type; }
      set { _rank_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_rank_qurey_reply")]
  public partial class sc_rank_qurey_reply : global::ProtoBuf.IExtensible
  {
    public sc_rank_qurey_reply() {}
    
    private uint _rank_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rank_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank_type
    {
      get { return _rank_type; }
      set { _rank_type = value; }
    }
    private uint _my_rank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"my_rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint my_rank
    {
      get { return _my_rank; }
      set { _my_rank = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_rank_info> _rank_info_list = new global::System.Collections.Generic.List<network.pb_rank_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rank_info_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_rank_info> rank_info_list
    {
      get { return _rank_info_list; }
    }
  

    private uint _pool = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pool", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pool
    {
      get { return _pool; }
      set { _pool = value; }
    }

    private uint _my_recharge_money = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"my_recharge_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint my_recharge_money
    {
      get { return _my_recharge_money; }
      set { _my_recharge_money = value; }
    }

    private uint _start_time = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint start_time
    {
      get { return _start_time; }
      set { _start_time = value; }
    }

    private uint _end_time = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_rank_info")]
  public partial class pb_rank_info : global::ProtoBuf.IExtensible
  {
    public pb_rank_info() {}
    
    private uint _rank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private string _player_uuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_uuid
    {
      get { return _player_uuid; }
      set { _player_uuid = value; }
    }
    private byte[] _player_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }
    private string _player_icon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"player_icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_icon
    {
      get { return _player_icon; }
      set { _player_icon = value; }
    }
    private uint _player_vip;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"player_vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player_vip
    {
      get { return _player_vip; }
      set { _player_vip = value; }
    }

    private ulong _gold_num = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gold_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong gold_num
    {
      get { return _gold_num; }
      set { _gold_num = value; }
    }

    private ulong _win_gold_num = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"win_gold_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong win_gold_num
    {
      get { return _win_gold_num; }
      set { _win_gold_num = value; }
    }

    private ulong _cash_num = default(ulong);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"cash_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong cash_num
    {
      get { return _cash_num; }
      set { _cash_num = value; }
    }

    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }

    private ulong _hundred_win = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"hundred_win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong hundred_win
    {
      get { return _hundred_win; }
      set { _hundred_win = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_vip_daily_reward")]
  public partial class cs_vip_daily_reward : global::ProtoBuf.IExtensible
  {
    public cs_vip_daily_reward() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_vip_daily_reward")]
  public partial class sc_vip_daily_reward : global::ProtoBuf.IExtensible
  {
    public sc_vip_daily_reward() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _rewards = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> rewards
    {
      get { return _rewards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_guide_info_update")]
  public partial class sc_guide_info_update : global::ProtoBuf.IExtensible
  {
    public sc_guide_info_update() {}
    
    private uint _step_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"step_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint step_id
    {
      get { return _step_id; }
      set { _step_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_guide_next_step_req")]
  public partial class cs_guide_next_step_req : global::ProtoBuf.IExtensible
  {
    public cs_guide_next_step_req() {}
    
    private uint _next_step_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"next_step_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint next_step_id
    {
      get { return _next_step_id; }
      set { _next_step_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_guide_next_step_reply")]
  public partial class sc_guide_next_step_reply : global::ProtoBuf.IExtensible
  {
    public sc_guide_next_step_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _reward = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> reward
    {
      get { return _reward; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_hundred_last_week_rank_query_req")]
  public partial class cs_hundred_last_week_rank_query_req : global::ProtoBuf.IExtensible
  {
    public cs_hundred_last_week_rank_query_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_hundred_last_week_rank_query_reply")]
  public partial class sc_hundred_last_week_rank_query_reply : global::ProtoBuf.IExtensible
  {
    public sc_hundred_last_week_rank_query_reply() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_hundred_last_week_data> _list = new global::System.Collections.Generic.List<network.pb_hundred_last_week_data>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_hundred_last_week_data> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_hundred_last_week_data")]
  public partial class pb_hundred_last_week_data : global::ProtoBuf.IExtensible
  {
    public pb_hundred_last_week_data() {}
    
    private uint _rank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private ulong _reward_gold;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reward_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong reward_gold
    {
      get { return _reward_gold; }
      set { _reward_gold = value; }
    }
    private byte[] _name1_round_win;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name1_round_win", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name1_round_win
    {
      get { return _name1_round_win; }
      set { _name1_round_win = value; }
    }
    private byte[] _name2_total_win;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name2_total_win", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name2_total_win
    {
      get { return _name2_total_win; }
      set { _name2_total_win = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_real_name_update")]
  public partial class cs_real_name_update : global::ProtoBuf.IExtensible
  {
    public cs_real_name_update() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _id_card_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id_card_num", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id_card_num
    {
      get { return _id_card_num; }
      set { _id_card_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_real_name_update")]
  public partial class sc_real_name_update : global::ProtoBuf.IExtensible
  {
    public sc_real_name_update() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _rewards = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> rewards
    {
      get { return _rewards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_real_name_req")]
  public partial class cs_real_name_req : global::ProtoBuf.IExtensible
  {
    public cs_real_name_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_real_name_req")]
  public partial class sc_real_name_req : global::ProtoBuf.IExtensible
  {
    public sc_real_name_req() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}