//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: prize_exchange.proto
// Note: requires additional types generated from: item.proto
namespace network
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_prize_config_update")]
  public partial class sc_prize_config_update : global::ProtoBuf.IExtensible
  {
    public sc_prize_config_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_prize_info> _list = new global::System.Collections.Generic.List<network.pb_prize_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_prize_info> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_prize_info")]
  public partial class pb_prize_info : global::ProtoBuf.IExtensible
  {
    public pb_prize_info() {}
    
    private uint _obj_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _need_item_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"need_item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint need_item_id
    {
      get { return _need_item_id; }
      set { _need_item_id = value; }
    }
    private ulong _need_item_num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"need_item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong need_item_num
    {
      get { return _need_item_num; }
      set { _need_item_num = value; }
    }
    private uint _need_vip_level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"need_vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint need_vip_level
    {
      get { return _need_vip_level; }
      set { _need_vip_level = value; }
    }
    private string _icon;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private uint _tag;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"tag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tag
    {
      get { return _tag; }
      set { _tag = value; }
    }
    private uint _cls;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"cls", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cls
    {
      get { return _cls; }
      set { _cls = value; }
    }
    private byte[] _dsc;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"dsc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] dsc
    {
      get { return _dsc; }
      set { _dsc = value; }
    }
    private uint _today_buy_times;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"today_buy_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint today_buy_times
    {
      get { return _today_buy_times; }
      set { _today_buy_times = value; }
    }
    private int _sort_id;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"sort_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sort_id
    {
      get { return _sort_id; }
      set { _sort_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_prize_query_one_req")]
  public partial class cs_prize_query_one_req : global::ProtoBuf.IExtensible
  {
    public cs_prize_query_one_req() {}
    
    private uint _obj_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_prize_query_one_reply")]
  public partial class sc_prize_query_one_reply : global::ProtoBuf.IExtensible
  {
    public sc_prize_query_one_reply() {}
    
    private uint _obj_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }
    private uint _day_times_config;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"day_times_config", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint day_times_config
    {
      get { return _day_times_config; }
      set { _day_times_config = value; }
    }
    private uint _today_exchange_times;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"today_exchange_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint today_exchange_times
    {
      get { return _today_exchange_times; }
      set { _today_exchange_times = value; }
    }
    private uint _store_num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"store_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint store_num
    {
      get { return _store_num; }
      set { _store_num = value; }
    }
    private uint _crad_num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"crad_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint crad_num
    {
      get { return _crad_num; }
      set { _crad_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_prize_exchange_req")]
  public partial class cs_prize_exchange_req : global::ProtoBuf.IExtensible
  {
    public cs_prize_exchange_req() {}
    
    private uint _obj_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }

    private uint _phone_card_charge_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"phone_card_charge_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint phone_card_charge_type
    {
      get { return _phone_card_charge_type; }
      set { _phone_card_charge_type = value; }
    }

    private string _phone_number = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"phone_number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string phone_number
    {
      get { return _phone_number; }
      set { _phone_number = value; }
    }

    private uint _address_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"address_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint address_id
    {
      get { return _address_id; }
      set { _address_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_prize_exchange_reply")]
  public partial class sc_prize_exchange_reply : global::ProtoBuf.IExtensible
  {
    public sc_prize_exchange_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private byte[] _err;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _reward = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> reward
    {
      get { return _reward; }
    }
  
    private uint _obj_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_prize_exchange_record_update")]
  public partial class sc_prize_exchange_record_update : global::ProtoBuf.IExtensible
  {
    public sc_prize_exchange_record_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_prize_exchange_record> _list = new global::System.Collections.Generic.List<network.pb_prize_exchange_record>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_prize_exchange_record> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_prize_exchange_record")]
  public partial class pb_prize_exchange_record : global::ProtoBuf.IExtensible
  {
    public pb_prize_exchange_record() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _record_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"record_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint record_type
    {
      get { return _record_type; }
      set { _record_type = value; }
    }
    private uint _obj_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }
    private uint _need_item_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"need_item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint need_item_id
    {
      get { return _need_item_id; }
      set { _need_item_id = value; }
    }
    private ulong _need_item_num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"need_item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong need_item_num
    {
      get { return _need_item_num; }
      set { _need_item_num = value; }
    }
    private uint _second_time;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"second_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint second_time
    {
      get { return _second_time; }
      set { _second_time = value; }
    }

    private uint _recharge_type = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"recharge_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint recharge_type
    {
      get { return _recharge_type; }
      set { _recharge_type = value; }
    }

    private uint _recharge_state = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"recharge_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint recharge_state
    {
      get { return _recharge_state; }
      set { _recharge_state = value; }
    }

    private string _card_number = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"card_number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string card_number
    {
      get { return _card_number; }
      set { _card_number = value; }
    }

    private string _card_psd = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"card_psd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string card_psd
    {
      get { return _card_psd; }
      set { _card_psd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_prize_address_info_update")]
  public partial class sc_prize_address_info_update : global::ProtoBuf.IExtensible
  {
    public sc_prize_address_info_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_prize_address_info> _list = new global::System.Collections.Generic.List<network.pb_prize_address_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_prize_address_info> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_prize_address_info")]
  public partial class pb_prize_address_info : global::ProtoBuf.IExtensible
  {
    public pb_prize_address_info() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private byte[] _province_name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"province_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] province_name
    {
      get { return _province_name; }
      set { _province_name = value; }
    }
    private byte[] _city_name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"city_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] city_name
    {
      get { return _city_name; }
      set { _city_name = value; }
    }
    private byte[] _address;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] address
    {
      get { return _address; }
      set { _address = value; }
    }
    private byte[] _phone_number;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"phone_number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] phone_number
    {
      get { return _phone_number; }
      set { _phone_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_prize_address_change_req")]
  public partial class cs_prize_address_change_req : global::ProtoBuf.IExtensible
  {
    public cs_prize_address_change_req() {}
    
    private network.pb_prize_address_info _new_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"new_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public network.pb_prize_address_info new_info
    {
      get { return _new_info; }
      set { _new_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_prize_address_change_reply")]
  public partial class sc_prize_address_change_reply : global::ProtoBuf.IExtensible
  {
    public sc_prize_address_change_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private byte[] _err;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_prize_storage_red_point_update")]
  public partial class sc_prize_storage_red_point_update : global::ProtoBuf.IExtensible
  {
    public sc_prize_storage_red_point_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_prize_query_one> _list = new global::System.Collections.Generic.List<network.pb_prize_query_one>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_prize_query_one> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_prize_query_one")]
  public partial class pb_prize_query_one : global::ProtoBuf.IExtensible
  {
    public pb_prize_query_one() {}
    
    private uint _obj_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }
    private uint _store_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"store_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint store_num
    {
      get { return _store_num; }
      set { _store_num = value; }
    }
    private uint _crad_num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"crad_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint crad_num
    {
      get { return _crad_num; }
      set { _crad_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_prize_query_phonecard_key_req")]
  public partial class cs_prize_query_phonecard_key_req : global::ProtoBuf.IExtensible
  {
    public cs_prize_query_phonecard_key_req() {}
    
    private string _rec_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rec_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rec_id
    {
      get { return _rec_id; }
      set { _rec_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_prize_query_phonecard_key_reply")]
  public partial class sc_prize_query_phonecard_key_reply : global::ProtoBuf.IExtensible
  {
    public sc_prize_query_phonecard_key_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private byte[] _err;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private string _key;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}