//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Research.proto
namespace Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CResearchSynthesisRequest")]
  public partial class CS_CResearchSynthesisRequest : global::ProtoBuf.IExtensible
  {
    public CS_CResearchSynthesisRequest() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CResearchTimeoutRequest")]
  public partial class CS_CResearchTimeoutRequest : global::ProtoBuf.IExtensible
  {
    public CS_CResearchTimeoutRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CResearchInfoResponse")]
  public partial class SC_CResearchInfoResponse : global::ProtoBuf.IExtensible
  {
    public SC_CResearchInfoResponse() {}
    
    private int _remainTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"remainTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int remainTime
    {
      get { return _remainTime; }
      set { _remainTime = value; }
    }
    private int _itemId1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemId1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId1
    {
      get { return _itemId1; }
      set { _itemId1 = value; }
    }
    private int _status1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"status1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status1
    {
      get { return _status1; }
      set { _status1 = value; }
    }
    private int _itemId2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"itemId2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId2
    {
      get { return _itemId2; }
      set { _itemId2 = value; }
    }
    private int _status2;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"status2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status2
    {
      get { return _status2; }
      set { _status2 = value; }
    }
    private int _itemId3;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"itemId3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId3
    {
      get { return _itemId3; }
      set { _itemId3 = value; }
    }
    private int _status3;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"status3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status3
    {
      get { return _status3; }
      set { _status3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}