//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: share.proto
// Note: requires additional types generated from: item.proto
namespace network
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_share_new_bee_reward_req")]
  public partial class cs_share_new_bee_reward_req : global::ProtoBuf.IExtensible
  {
    public cs_share_new_bee_reward_req() {}
    
    private string _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_share_new_bee_reward_reply")]
  public partial class sc_share_new_bee_reward_reply : global::ProtoBuf.IExtensible
  {
    public sc_share_new_bee_reward_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _rewards = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> rewards
    {
      get { return _rewards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_share_mission_reward_req")]
  public partial class cs_share_mission_reward_req : global::ProtoBuf.IExtensible
  {
    public cs_share_mission_reward_req() {}
    
    private string _friend_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_share_mission_reward_reply")]
  public partial class sc_share_mission_reward_reply : global::ProtoBuf.IExtensible
  {
    public sc_share_mission_reward_reply() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _rewards = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> rewards
    {
      get { return _rewards; }
    }
  
    private string _friend_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_share_mission")]
  public partial class pb_share_mission : global::ProtoBuf.IExtensible
  {
    public pb_share_mission() {}
    
    private string _friend_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _head;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string head
    {
      get { return _head; }
      set { _head = value; }
    }
    private int _vip_lv;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"vip_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vip_lv
    {
      get { return _vip_lv; }
      set { _vip_lv = value; }
    }
    private string _title;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_share_info")]
  public partial class sc_share_info : global::ProtoBuf.IExtensible
  {
    public sc_share_info() {}
    
    private string _my_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"my_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string my_code
    {
      get { return _my_code; }
      set { _my_code = value; }
    }
    private string _code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private bool _free;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"free", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool free
    {
      get { return _free; }
      set { _free = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_share_mission> _list = new global::System.Collections.Generic.List<network.pb_share_mission>();
    [global::ProtoBuf.ProtoMember(5, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_share_mission> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_share_mission_update")]
  public partial class sc_share_mission_update : global::ProtoBuf.IExtensible
  {
    public sc_share_mission_update() {}
    
    private readonly global::System.Collections.Generic.List<network.pb_share_mission> _list = new global::System.Collections.Generic.List<network.pb_share_mission>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_share_mission> list
    {
      get { return _list; }
    }
  
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_share_draw_request")]
  public partial class cs_share_draw_request : global::ProtoBuf.IExtensible
  {
    public cs_share_draw_request() {}
    
    private int _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_share_friend_request")]
  public partial class cs_share_friend_request : global::ProtoBuf.IExtensible
  {
    public cs_share_friend_request() {}
    
    private int _page;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }

    private string _user_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_share_rank_request")]
  public partial class cs_share_rank_request : global::ProtoBuf.IExtensible
  {
    public cs_share_rank_request() {}
    
    private int _page;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_share_draw_response")]
  public partial class sc_share_draw_response : global::ProtoBuf.IExtensible
  {
    public sc_share_draw_response() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private int _index;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_share_history_item_response")]
  public partial class pb_share_history_item_response : global::ProtoBuf.IExtensible
  {
    public pb_share_history_item_response() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _process;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"process", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int process
    {
      get { return _process; }
      set { _process = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_share_history_friend_item_response")]
  public partial class pb_share_history_friend_item_response : global::ProtoBuf.IExtensible
  {
    public pb_share_history_friend_item_response() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _create_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"create_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int create_time
    {
      get { return _create_time; }
      set { _create_time = value; }
    }
    private int _first_day;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"first_day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int first_day
    {
      get { return _first_day; }
      set { _first_day = value; }
    }
    private int _three_day;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"three_day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int three_day
    {
      get { return _three_day; }
      set { _three_day = value; }
    }
    private int _seven_day;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"seven_day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seven_day
    {
      get { return _seven_day; }
      set { _seven_day = value; }
    }
    private int _is_red;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"is_red", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int is_red
    {
      get { return _is_red; }
      set { _is_red = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_share_history_response")]
  public partial class sc_share_history_response : global::ProtoBuf.IExtensible
  {
    public sc_share_history_response() {}
    
    private int _count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private int _one_draw;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"one_draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int one_draw
    {
      get { return _one_draw; }
      set { _one_draw = value; }
    }
    private int _three_draw;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"three_draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int three_draw
    {
      get { return _three_draw; }
      set { _three_draw = value; }
    }
    private int _seven_draw;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"seven_draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seven_draw
    {
      get { return _seven_draw; }
      set { _seven_draw = value; }
    }
    private int _pages;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pages", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pages
    {
      get { return _pages; }
      set { _pages = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_share_history_friend_item_response> _list = new global::System.Collections.Generic.List<network.pb_share_history_friend_item_response>();
    [global::ProtoBuf.ProtoMember(6, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_share_history_friend_item_response> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pb_share_rank_item_response")]
  public partial class pb_share_rank_item_response : global::ProtoBuf.IExtensible
  {
    public pb_share_rank_item_response() {}
    
    private int _rank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_share_rank_response")]
  public partial class sc_share_rank_response : global::ProtoBuf.IExtensible
  {
    public sc_share_rank_response() {}
    
    private int _count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private int _rank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private int _pages;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pages", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pages
    {
      get { return _pages; }
      set { _pages = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_share_rank_item_response> _list = new global::System.Collections.Generic.List<network.pb_share_rank_item_response>();
    [global::ProtoBuf.ProtoMember(4, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_share_rank_item_response> list
    {
      get { return _list; }
    }
  

    private int _beginTime = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"beginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int beginTime
    {
      get { return _beginTime; }
      set { _beginTime = value; }
    }

    private int _endTime = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_draw_count_response")]
  public partial class sc_draw_count_response : global::ProtoBuf.IExtensible
  {
    public sc_draw_count_response() {}
    
    private int _draw_count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"draw_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw_count
    {
      get { return _draw_count; }
      set { _draw_count = value; }
    }
    private int _draw_count_seven;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"draw_count_seven", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw_count_seven
    {
      get { return _draw_count_seven; }
      set { _draw_count_seven = value; }
    }
    private int _draw_count_one;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"draw_count_one", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw_count_one
    {
      get { return _draw_count_one; }
      set { _draw_count_one = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_task_seven_info_response")]
  public partial class sc_task_seven_info_response : global::ProtoBuf.IExtensible
  {
    public sc_task_seven_info_response() {}
    
    private int _task_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int task_id
    {
      get { return _task_id; }
      set { _task_id = value; }
    }
    private int _process;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"process", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int process
    {
      get { return _process; }
      set { _process = value; }
    }

    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }

    private int _award = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"award", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int award
    {
      get { return _award; }
      set { _award = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_task_seven_award_request")]
  public partial class cs_task_seven_award_request : global::ProtoBuf.IExtensible
  {
    public cs_task_seven_award_request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_task_seven_award_response")]
  public partial class sc_task_seven_award_response : global::ProtoBuf.IExtensible
  {
    public sc_task_seven_award_response() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private byte[] _err = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<network.pb_reward_info> _rewards = new global::System.Collections.Generic.List<network.pb_reward_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<network.pb_reward_info> rewards
    {
      get { return _rewards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_share_with_friends_req")]
  public partial class cs_share_with_friends_req : global::ProtoBuf.IExtensible
  {
    public cs_share_with_friends_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}