-- -----------------------------------------------------------------


-- *
-- * Filename:    luaTextConfig.lua
-- * Summary:     文字本地化，同GameText
-- *
-- * Version:     1.0.0
-- * Author:      HAN-PC
-- * Date:        2016-11-29 15:33:32
-- -----------------------------------------------------------------

local M =
{
    -- 等级礼包
    lv_gift_title = "{0}级礼包",
    month_gift_title = "{0}/天",
    month_day_last = "剩余{0}天可领",
    activity_btn_recharge = "购买",
    activity_btn_get = "领取",
    room_state_10 = "等待加入 {0}",
    room_state_11 = "准备开始 {0}",
    room_state_20 = "抢庄中 {0}",
    room_state_21 = "等待庄家 {0}",
    room_state_30 = "闲家下注 {0}",
    room_state_40 = "",
    room_state_50 = "",
    cow_type_0 = "没牛",
    cow_type_1 = "牛一",
    cow_type_2 = "牛二",
    cow_type_3 = "牛三",
    cow_type_4 = "牛四",
    cow_type_5 = "牛五",
    cow_type_6 = "牛六",
    cow_type_7 = "牛七",
    cow_type_8 = "牛八",
    cow_type_9 = "牛九",
    cow_type_10 = "牛牛",
    cow_type_11 = "四炸",
    cow_type_12 = "五花牛",
    cow_type_13 = "五小牛",
    cow_game_times_tip = "再玩{0}局",
    cow_helper_tip = "[e26102]{0}[-] [522b22]即将为你开牌[-]",
    room_back_to_enter_tip = "之前的游戏还未结束，是否为您恢复？",
    hundred_start_tip = "连庄{0}次",
    hundred_state_tip_0 = "休息一下",
    hundred_state_tip_1 = "请下注",
    hundred_state_tip_2 = "牌局结算中",
    hundred_my_bet_tip_0 = "[e3e3e3]没有下注[-]",
    hundred_my_bet_tip_1 = "[fffb66]x{0}          {1}[-]",
    hundred_seat_limit_tip = "金币需要大于50万才可上座哦",
    hundred_seat_state_limit_tip = "下注和等待开始阶段才可上座哦",
    hundred_player_list_layer_title = "[904c1d]当前无座玩家共[-]  [e36500]{0}[-]  [904c1d]人[-]",
    hundred_dealer_layer_tip = "[ae9d8a]上庄至少需要  [e36500]{0}[-]  金币[-]",
    hundred_dealer_get_btn_up = "我要上庄",
    hundred_dealer_get_btn_down = "取消上庄",
    chat_win_default_text = "输入消息",
    open_box_win_tip = "[7d3c15]你需要保留[-][f25221]{0}金币[-][7d3c15]以便正常游戏[-]",
    open_box_win_tip2 = "已领取次数：[9eff2b]{0}/{1}[-]",
    open_box_win_tip3 = "购买福袋可增加额外5次免费领取次数，是否前往购买？",
    fast_add_gold_tip = "额外赠送[fffc00]{0}[-]金币",
    fast_add_gold_btn_tip = "原价:{0}.00",
    initingLoadXml = "正在加载游戏配置...{0}%(不产生流量)",
    loadingNotice = "加载公告",
    cancel = "取消",
    canceled = "已取消",
    canceled2 = "（已取消）",
    loginTip1 = "登录帐号服务器成功",
    loginTip2 = "注册帐号成功",
    connect_account_server_failed = "连接帐号服务器失败",
    test1 = "<bat:%s name:%s>",
    test = "测试",
    userName = "账户:",
    server = "服务器:",
    loginGame = "进入游戏",
    fasetLogin = "快速进入",
    password = "密码:",
    surePassword = "确认密码:",
    ErrorMsg1121 = "[FF0000]夺要标有[-]",
    messageDialog_tip = "提示",
    messageDialog_ok = "确定",
    messageDialog_no = "取消",
    messageDialog_back = "取消",
    recommend_Servers = "推荐服务器",
    open_lv_lmt_unknow_lv = "功能未开启",
    login_errorCode = "(错误码:{0})",
    btn_fresh = "刷新",
    btn_send = "发送",
    socket_connect_failed = "网络连接失败，请检查网络后重试。",
    socket_connect_timeout = "网络连接超时，请检查网络后重试。",
    disconect_login_failed = "登录服务器失败，请检查网络后再登录。",
    disconect_login_timeout = "登录服务器超时，请检查网络后再登录。",
    reconnect_failed = "重新连接网络失败，请检查网络后重新登录。",
    reconnect_timeout = "重新连接网络超时，请检查网络后重新登录。",
    msg_reconnect_failed = "重新连接失败，请检查网络后重新登录。",
    msg_reconnect_timeout = "重新连接超时，请检查网络后重新登录。",
    login_in_other_place = "您的帐号已在其他地方登录！",
    socket_disconnect = "网络连接断开，请检查网络后重试。",
    leave_long_time = "您已离开游戏太久, 请重新登录。",
    socket_connect_bad = "连接超时, 请重新登录。",
    loading_tip1 = "[99F634]小提示：[-]合理的阵容搭配将提升战斗力。",
    loading_tip2 = "[99F634]小提示：[-]记得每天都有不同的战役可以挑战。",
    loading_tip3 = "[99F634]小提示：[-]记得每天12:00，18:00，21:00有包子可领哦。",
    loading_tip4 = "[99F634]小提示：[-]完成每日任务能得到大量经验，可迅速提升等级！",
    loading_tip5 = "[99F634]小提示：[-]当遇到游戏困难时，记住:得稀有武将，氪能改命！",
    loading_tip6 = "[99F634]小提示：[-]强化武器，可大幅提升战斗力！",
    loading_tip7 = "[99F634]小提示：[-]镶嵌符文，战斗更加轻松。",
    loading_tip8 = "[99F634]小提示：[-]装备可是有套装属性的，记住哦。",
    loading_tip9 = "[99F634]小提示：[-]每天第一次购买金币和包子非常实惠。",
    loading_tip10 = "[99F634]小提示：[-]在竞技场争取到好名次，闪闪发光的元宝在向你招手~",
    login_name_empty = "请输入手机号！",
    login_name_default = "在此输入您的手机号",
    login_passWord_empty = "请输入6-16位数字或字母作为密码！",
    login_passWord_default = "请输入6-16位密码",
    reset_passWord_default = "请输入6-16位密码",
    please_input_right_phone_num = "请输入正确的手机号码",
    touris_login_tip = "[904c1d]您已使用[-][e36500][游客身份][-][904c1d]登录，游客数据可能在游戏升级或重装后丢失，为了您的账号安全请绑定手机，首次绑定手机号码后即可获赠[-][e36500]10000金币[-][904c1d]，绑定操作不会扣除您任何费用，请您放心。[-]",
    btn_sure = "确定",
    btn_register = "注册",
    phone_lb = "手机号",
    new_passWord_lb = "新密码",
    verification_lb = "验证码",
    password_lb = "密    码",
    goto_lb = "前往",
    old_password = "旧密码",
    old_password_default = "请输入当前密码",
    new_password = "新密码",
    new_password_default = "请输入6-12位密码",
    register_binding_tip = "免费绑定手机转注册用户，获赠10000金币！",
    verify_default = "请输入语音验证码",
    verify_get = "获取验证码",
    verify_wait = "重新获取({0}s)",
    try_later = "倒计时结束后再试",
    change_password_succ = "修改成功",
    LvText = "Lv.{0}",
    wan = "万",
    yi = "亿",
    player_info_desc1 = "确定",
    player_info_desc2 = "您已成功兑换红包",
    player_info_desc3 = "[522b22]扫描二维码或搜索[-][ff3e12]“天添网络”[-][522b22]前往公众号领取红包奖励。[-]",
    player_info_desc4 = "",--[ff3e12]每日首次兑换红包，100%获得额外金币奖励[-]
    exit_game_message = "是否退出游戏",
    quick_start_lb = "快速开始",
    version_show_lb = "版本号:{0}",
    room_select_gold_too_much = "您的金币太多了~请前往{0}赚金，不要欺负新手哦！",
    room_select_gold_noEnough = "您的金币不足，需要{0}以上的金币，是否前往购买？",
    to_room_go = "去",
    StrFilter_failed = "昵称存在敏感词，请重新填写！",
    playerInfoTab0 = "基本信息",
    playerInfoTab1 = "我的道具",
    playerInfoHeadTip = "点击修改头像",
    changePassWord = "修改密码",
    playerInfoLv = "等级：{0}",
    playerInfoSex = "性别：",
    playerInfoName = "性别：",
    infoChangeLb = "修改资料",
    infoCommitLb = "提交资料",
    playerWin = "胜率：{0}%    {1}胜 {2}负",
    playerMaxMoney = "最大财富：{0}",
    playerTotalProfit = "[904c1d]总盈利：[-][47ac23]{0}[-]",
    playerWeekProfit = "[904c1d]（本周：[-][e5281a]{0}[-][904c1d]）[-]",
    playerNiuTenNum = "牛牛次数：   {0}",
    playerBombNum = "四炸次数：   {0}",
    playerFiftyNum = "五花牛次数：   {0}",
    playerFiveSmallNum = "五小牛次数：   {0}",
    playerOtherNum = "没牛获胜次数：   {0}",
    playerAccount = "（玩家号：{0}）",
    changeNameTip = "每位玩家只能进行一次改名（本次免费），是否确认修改？",
    changeNameFailed = "修改昵称失败",
    changeNameFailed1 = "该昵称已存在，修改失败！",
    changeNameFailed2 = "昵称存在敏感词，请重新填写！",
    changeNameFailed3 = "修改昵称失败,改名卡不足",
    changeNameFailed4 = "修改昵称失败,昵称不能为空",
    changeNameFailed5 = "修改昵称失败,昵称超过6个字",
    changeNameFailed6 = "修改昵称失败,跟旧的相同",
    changeSexFailed = "修改性别失败",
    changeNameAndSex = "资料修改成功",
    headIconUp_failed = "上传头像失败",
    headIconUp_finished = "上传头像结束",
    headIcon_selected_failed = "头像选择失败",
    btnBindingPhone = "绑定手机",
    BindingPhoneTip = "绑定送10000",
    BindingPhoneID = "实名认证送5000",
    btnAddFriend = "加好友",
    OtherWinLose = "[b1906e]战绩:[-][904c1d]{0}胜 {1}负[-]",
    OtherWinRate = "[b1906e]胜率:[-][904c1d]{0}%[-]",
    OtherWeekProfit = "[ae9d8a]本周盈利:[-][47ac2d]{0}[-]",
    otherPlayerLv = "LV{0}",
    magicFaceLb = "魔法表情，每次使用消耗20金币",
    bug_feedback_desc1 = "反馈",
    bug_feedback = "Bug反馈",
    bug_feedback_default = "请输入反馈内容",
    bug_feedback_empty = "请输入要反馈的内容",
    bug_feedback_succ = "反馈成功！",
    bug_feedback_failed2 = "cd时间不得低于60s！",
    bug_feedback_failed3 = "Bug内容字数限制！",
    bug_feedback_failed4 = "其他原因提交失败！",
    Sex0 = "男",
    Sex1 = "女",
    Game1 = "牛牛大战",
    Game2 = "百人大战",
    subsidy_tip = "今日还可领取{0}次（共{1}次）",
    pic_select_title = "图片来源",
    pic_select_albumLb = "手机相册",
    pic_select_phonegraphLb = "手机拍照",
    free_subsidy_name = "[904c1d]破产补助[-][904c1d]（每日[-][e36500]{0}[-][904c1d]次，剩余[-][e36500]{1}[-][904c1d]次）[-]",
    get = "领取",
    geted = "已领取",
    vip_get = "获取",
    vip_shop_tip = "[ffefd3]尊贵的[-][ffffff]{0}[-][ffefd3]玩家，您再充值[-][ffffff]{1}[-][ffefd3]元即可成为VIP，享受更多特权！[-]",
    vip_shop_tip2 = "[ffefd3]尊贵的[-][ffffff]{0}[-][ffefd3]玩家，您已充值[-][fcff00]{1}[-][ffefd3]元正在享受VIP{2}特权！[-]",
    shop_tab_gold = "金币",
    shop_tab_diamond = "钻石",
    shop_tab_item = "道具",
    shop_tab_vip = "VIP",
    shop_tab_vipgift = "VIP特惠",
    shop_buy_succ = "购买成功",
    shop_old_price = "原价:{0}",
    shop_item_extra = "赠送{0}%",
    shop_item_extra1 = "赠送{0}钻石",
    shop_item_limit = "每日限购：{0}次",
    setting_change_account = "切换账号",
    setting_help = "帮助",
    setting_feedback = "反馈",
    newTask = "新手任务",
    dailyTask = "今日任务",
    weekTask = "本周任务",
    timeTask = "定时任务",
    diamondTask = "钻石任务",
    emptyMail = "咦~还没有人给我写邮件",
    emptyMail2 = "邮件最多保留15天",
    mailTime = "有效期:",
    dayTime = "{0}天",
    hourTime = "{0}小时",
    minuteTime = "{0}分",
    rank1 = "财富榜",
    rank2 = "盈利榜",
    rank3 = "钻石榜",
    rankTip1 = "金币财富最多的牛人排名",
    rankTip2 = "今日赢金币最多的牛人排名",
    rankTip3 = "钻石财富最多的牛人排名",
    noEnough101 = "金币不足，请补充金币哦",
    noEnough102 = "钻石不足，请补充钻石哦",
    noEnough103 = "奖券不足，请补充奖券哦",
    noEnough109 = "红包不足，快去参加活动吧",
    exchange_tip = "[904c1d]千人红包场连续游戏[-][e36500]5[-][904c1d]局，[-][e36500]100%[-][904c1d]获得红包奖励[-]",
    exchange_card_no_enough = "库存不足",
    exchange_address = "[u]管理地址[/u]",
    exchange_look_btn = "查看",
    exchange_rechange_btn = "直充",
    exchange_title1 = "管理地址",
    exchange_title2 = "确认兑换",
    exchange_title3 = "充值方式",
    exchange_title4 = "充值号码",
    exchange_title5 = "Q币兑换",
    exchange_desc1 = "QQ号码",
    exchange_desc2 = "请输入QQ号码",
    exchangeTab1 = "红包",
    exchangeTab2 = "话费",
    exchangeTab3 = "实物",
    exchangeTab5 = "虚拟卡",
    exchangeNeed = "[904c1b]兑换消耗[-][ffb31f]{0}[-]",
    exchangeNeed2 = "[904c1b]兑换消耗：[-]",
    exchangeLimit = "每日限购：{0}",
    exchangeSureLimit = "[b08258]每日兑换次数：[-][b08258]{0}[-]",
    exchangeEmpty = "您什么都还没有哦！",
    exchangeAddressTip = "当您兑换实物奖励时将默认使用该地址信息，请您认真填写",
    exchangeTourise = "注册用户才可使用兑换功能",
    exchangeRedBagSucc = "兑换成功，请前往微信公众号领取",
    addr_name = "姓名",
    addr_sex = "性别",
    addr_city = "所在城市",
    addr_address = "详细地址",
    addr_phone = "手机号码",
    addr_name_empty = "请输入姓名",
    addr_city_empty = "请输入所在城市",
    addr_addr_empty = "请输入详细地址",
    addr_phone_empty = "请输入手机号码",
    addr_phone_check = "请输入正确手机号码",
    girl = "女",
    boy = "男",
    exchangeSureNeed = "[b08258]兑换需消耗[-][ffb31f]{0}[-]",
    exchangeSureLeft = "[b08258]库存:[-][b08258]{0}[-]",
    exchangeSureLeftNo = "[ae9d8a]库存:[-][ffb31f]{0}[-]",
    rechangeType_btn = "直充",
    rechargePhoneSucc = "兑换成功，请前往邮箱查看",
    addrSetSucc = "设置成功",
    exchangeVip = "需要VIP：{0}",
    vipNoMatch = "VIP等级不足",
    rechargeType_get = "提取卡密",
    exchangeSucc = "兑换成功",
    exchangeCardLooKWait = "等待工作人员处理",
    exchangeCardLooK = "卡号:{0}\n卡密:{1}",
    cardNumLink = "[u]复制卡号[/u]",
    passWordLink = "[u]复制密码[/u]",
    card_lb = "卡   号",
    password_lb = "密   码",
    copyCardSucc = "复制卡号成功",
    copyPsdSucc = "复制密码成功",
    onlySupportOnPhone = "该功能只在手机上支持",
    exchange_help_lb = "[u]兑换流程[/u]",
    exchange_help_tab1 = "红包兑换流程：",
    exchange_help_desc1 = "[b97e56]前往“天添网络”公众号（微信搜索“[-][f1411e]天添网络[-][b97e56]”并关注）--[-][f1411e]绑定游戏账号[-][b97e56]--[-][f1411e]领取红包[-]",
    exchange_help_tab2 = "话费兑换流程：",
    exchange_help_desc2 = "[b97e56]绑定手机账号--选择[-][f1411e]充值方式[-][b97e56]（直充/卡密）--[-][f1411e]工作人员审核[-][b97e56]（2个工作日内）--“直充”将直接充值/“卡密”在[-][f1411e]兑换记录[-][b97e56]中查看卡号密码[-]",
    exchange_help_tab3 = "实物兑换流程：",
    exchange_help_desc3 = "[b97e56]绑定手机账号--填写“[-][f1411e]默认收货地址[-][b97e56]”--[-][f1411e]工作人员审核[-][b97e56]（2个工作日内）--发货[-]",
    redBagTab1 = "红包广场",
    redBagTab2 = "通    知",
    redBagGuessTip = "金额介于10万-1亿",
    redBagSendTip = "[fff6e4]发红包需要[-][fdff63]VIP3[-][fff6e4]以上\n身上保留金币不得低于[-][aaff45]30.00[-][fff6e4]万\n红包金额需介于[-][aaff45]10万-1亿[-][fff6e4]\n最先猜中的玩家有机会获得红包\n当红包被玩家猜中后您会得到通知[-]",
    redBagSendTip2 = "红包金额需介于10万-1亿\n最先猜中的玩家有机会获得红包",
    redBagSendTip3 = "",
    redBagSendVipNoEnough = "发红包需要VIP3以上",
    redBagSendDefaultTitle = "恭喜发财，大吉大利！",
    redBagSendNumTip = "请输入红包金额",
    noTitle = "请输入红包名",
    noTitle2 = "最多输入10个中文字",
    redBagSendNumNoCorrect = "红包金额需介于10万-1亿",
    redBagSendSucc = "发红包成功！在通知中可查看红包动态！",
    redBagSendSure = "确认将{0}金币塞入红包?",
    redBagSendLeftMoney = "身上保留金币不得低于30万",
    redBagGuessTip = "猜猜红包有多大",
    redBagGuessDefault = "请输入红包金额",
    redBagGuessErr = "猜错了，再试试看！",
    redBagGuessVip = "VIP用户才可猜红包",
    redBagEmpty = "红包抢完啦，你来一发吧！",
    redBagGuessSuccWait = "已猜中，请等待发红包者确认！",
    redBagNoticeGuess = "[b1906e]被[ff6955]{0}[-][b1906e]猜中啦！是否把奖励给他[-]",
    guess_btn = "猜一猜",
    loginAwardTitle_1 = "第1天",
    loginAwardTitle_2 = "第2天",
    loginAwardTitle_3 = "第3天",
    loginAwardTitle_4 = "第4天",
    loginAwardTitle_5 = "第5天",
    loginAwardTitle_6 = "第6天",
    loginAwardTitle_7 = "第7天",
    loginAwardNotVipTips = "您还不是VIP，请先充值",
    loginAwardVipLevelUpTips = "还需             元升至",
    loginAwardVipTopLevelTips = "您已经是尊贵",  
    loginAwardVipAwardTips = "每日可领取                金币",
    loginAwardBtnToRecharge = "去充值",
    loginAwardBtnGetAward = "领取",
    loginAwardBtnMakeupGetAward = "补签",
    loginAwardBtnReceived = "已领取",
    loginAwardVipInfoSubTitle = "VIP等级达到指定级别，每日登录均可领取对应的VIP奖励",
    loginAwardVipInfoT1 = "每日可领取",
    loginAwardNotEnoughMakeupCards = "补签卡不足，是否前往商城购买？",
    loginAwardGotVipAward = "你已经领取过VIP奖励",
    loginAwardGotNormalAward = "你已经领取过登录奖励，请明天再来",
    help_tab1 = "基础玩法",
    help_desc1 = "[904c1d]1.每个玩家拥有5张手牌（但仅有5张手牌后才进行比较）\n2.如果你有3张手牌（JQK按10计算）相加为10的倍数（如10、20），即为有牛，否则为没牛。\n3.组成十后再看剩下2张牌相加的个位数，该数字越大则牌型越大。\n小提示：其他玩家分别和庄家比牌，牌大获胜！[-]",
    help_tab2 = "基础牌型",
    help_desc2 = "[904c1d]没牛：任意3张相加不为10的倍数。\n牛二：任意3张相加为10的倍数，另外2张相加个位数为2。\n牛牛：任意3张相加为10的倍数，另外2张相加为10倍数。\n炸弹：5张牌中有4张完全一样。\n五花牛：5张牌为花牌( JQK )。\n五小牛：5张牌均小于5，且相加之和不大于10。[-]",
    help_tab3 = "大小比较",
    help_desc3 = "[904c1d]1.基本牌型比较\n五小牛 > 五花牛> 炸弹 > 牛牛 > 有牛 > 没牛\n2. 组成十后的牌型比较\n牛九 > 牛八 > 牛七 > 牛六 > 牛五 > 牛四 > 牛三 > 牛二 > 牛一\n3. 牌型相同比较牌数字大小\nK > Q > J > 10 > 9 > 8 > 7 > 6 > 5 > 4 > 3 > 2 > A\n4. 数字相同比较花色大小。[-]",
    fruit_pool_info1 = "上轮头奖",
    fruit_pool_info2 = "奖金池：{0}",
    fruit_award_info1 = "奖励信息",
    fruit_award_info2 = "押线分布",
    fruit_award_info3 = "WILD可替代任何元素除了     和",
    fruit_award_info4 = "WILD",
    fruit_award_info5 = "连续3列出现       可获得",
    fruit_award_info6 = "单线投入2500以上，摇取3个可",
    fruit_award_info7 = "单线投入50000以上，摇取3个可",
    fruit_win_info1 = "请先投注",
    fruit_win_info2 = "免费模式无法变更投注金额及线数",
    fruit_win_info3 = "疯狂水果机，金币赢不停！",
    fruit_win_info4 = "金币不足，是否前往购买",
    fruit_win_info5 = "今天的任务已全部完成！",
    fruit_win_info6 = "连线数量",
    fruit_win_info7 = "单线投入",
    fruit_win_info8 = "上次中奖：",
    fruit_win_info9 = "领取所有宝箱奖励可激活下阶段任务",
    fruit_win_info10 = "VIP{0}可激活下阶段任务",


    fruit_box_tip0 = "完成宝箱任务，获得额外奖励",
    fruit_box_tip1 = "[fffffe]完成[-][c3ff5a]{0}[-][fffffe]个[-]" ,
    fruit_box_tip2 = "再完成{0}个任务，就能领奖了！",
    fruit_box_tip3 = "可以领奖啦！" ,
    fruit_box_tip4 = "水果狂欢，奖励不停！完成免费金币任务还有额外奖励哟！",
    fruit_box_tip5 = "累计赢取[fff600]{0}[-]金币",
    fruit_box_tip6 = "宝箱奖励每日0点重置",
    fruit_box_tip7 = "已领取",

    fruit_rank_desc1 = "名次",
    fruit_rank_desc2 = "玩家信息",
    fruit_rank_desc3 = "累计消耗",
    fruit_rank_desc4 = "可获得奖励",
    fruit_rank_desc5 = "获得奖励",

    fruit_rank_desc12 = "[956635]奖金池=总彩池-[-][ff4e2b]10亿[-][956635]， 若总彩池低于10亿则不瓜分奖金池，奖励每[-][ff4e2b]周一0点[-][956635]邮件发放[-]",
    fruit_rank_desc13 = "[956635]奖金池=总彩池-[-][ff4e2b]10亿[-][956635]， 若总彩池低于10亿则不瓜分奖金池，奖励每[-][ff4e2b]周一0点[-][956635]邮件发放[-]",
    
    fruit_rank_tab1 = "[FFFFFF]超级水果[-]",
    fruit_rank_tab2 = "[FFFFFF]上周中奖[-]",

    fruit_rank_tab_sel1 = "[FFFFFF]超级水果[-]",
    fruit_rank_tab_sel2 = "[FFFFFF]上周中奖[-]",

    fruit_into_limit = "玩“看牌抢庄”升至Lv.2可开启“水果狂欢”",
    battle_red_desc2 = "[1bfffc][u]可领取[/u][-]",
    mail_desc2 = "领取",

    car_into_limit = "玩“看牌抢庄”升至Lv.2并充值任意金额,可开启“豪车”",

    item_107 = "{0}元",
    strength_desc11 = "{0}/{1}",
    btn_get_money = "领取金币",
    btn_go_rechange = "立即充值",
    luckyCowSmallTip = "本次可招财",
    luckyCowSmallTip2 = "再充值{0}元可激活",
    luckyCowSmallTip3 = "今日累计赢金[cdff47]{0}/{1}[-]金币",
    luckyCowLeftTime = "倒计时：{0}",
    luckyCowTomorrow = "请明天再来",
    luckyCowTomorrow2 = "请先完成累计赢金任务",
    cowLv = "LV.{0}",
    luckyCowTip = "[ffbeab]1.充值就能获得招财金牛，完成每日赢金任务就可领取金币奖励。\n2.小金牛每天可招财一次,初始等级1级,[-][ffd45f]每次招财2000金币[-]\n[ffbeab]3.每累计充值10元可使金牛提升1级,[-][ffd45f]每次提升1级多招财200金币[-][ffbeab],等级越高,金牛招财越多,金牛每次招财封顶120万金币。   ",
    guide_answer_wrong = "不对哦，再想想！",
    month_card_buy = "立即购买",
    btn_get ="领取",
    btn_geted ="已领取",
    month_card_help = "1.至尊月卡每个帐号同时只能拥有一个，领取完月卡奖励之后才能购买下一个\n2.每日赠送需要到本页手动领取，如当日未领取则视为放弃奖励",

    -- /////////////////////////////////////////////////////////////////////////////
    -- 活动相关文字配置
    actAndAnnc_btn_awardGot = "已领取",
    actAndAnnc_btn_awardUnderay = "进行中",
    actAndAnnc_btn_awardComplete = "领取",
    actAndAnnc_msg_awardGot = "奖励已经领取",
    actAndAnnc_msg_awardUnderay = "尚未满足领取条件",
    funCreating = "功能未开放",


    -------
    normal_red_title = "已完成{0}/5局",
    normal_red_tip1 = "完成任务，可在红包雨来临时领取红包",
    normal_red_tip2 = "红包雨即将来临，请稍等片刻",

    -------
    btn_recover_lb = "去充值",
    btn_goGame_lb = "去游戏",
    red_condition_win_tip =  "[7d3c15]您当前钻石不足[-][f25221]18[-]",
    red_condition_win_tip3 = "[874c38]钻石不足[-][e36500]18[-][874c38]，前往商城充值继续赢取红包吧！[-]",
    red_condition_win_tip2 = "[874c38]您已完成全部任务，点击进入游戏[-]",
    red_condition_win_tip4 = "免费钻石",
    red_condition_win_tip5 = "充值钻石",
    red_condition_win_tip6 = "钻石任务",
    red_condition_win_tip7 = "[904c1d]可完成任务获得大量钻石奖励[-]",
    red_condition_win_tip8 = "[904c1d]购买钻石福袋\n当天免费复活一次[-]",
    red_condition_win_tip9 = "[904c1d]玩看牌抢庄[-][ff522a]免费[-][904c1d]领取钻石[-]",
    red_condition_win_tip10 = "[803d18]购买钻石[-]",
    red_condition_win_tip11 = "前往",
    red_condition_win_tip12 = "亲爱的用户，恭喜您复活成功。",
    red_condition_over = "今日任务次数已用完",
    diamond_bag_buy_lb = "立即购买",
    diamond_bag_buy_lb3 = "已购买",
    diamond_bag_buy_lb2 = "￥ 6.00",
    diamond_bag_has_buy = "每日限购一次",
    diamond_bag_tip = "购买后当日每次抢红包都有机会获得      元福袋奖励。\n购买当日赠送对局宝箱免费领取钻石次数：5次",
    diamond_bag_tip2 = "6",
    diamond_bag_tip3 = "每日首购赠送",
    
    shop_desc1="VIP{0} 才可购买",
  rich_car_tip1 ="弹幕" ,
  rich_car_tip2 ="成绩:", 
  rich_car_tip3 ="连庄:",
  rich_car_tip4 ="上庄" ,
  rich_car_tip5 ="开奖记录",
  rich_car_tip6 ="续压" ,
  rich_car_tip7 ="[18B159]{0}[-]",
  rich_car_tip8 ="[fa5353]{0}[-]",
  rich_car_tip9 ="        [fed007]{0}:[-][daeaf6]{1}[-]", 
  rich_car_tip10="[fed007]{0}:[-]",
  rich_car_tip11="[77ff65]玩家[-][1ad7ff]{0}[-][77ff65]进入了豪车俱乐部[-]", 
  rich_car_tip12="全部筹码", 
  rich_car_tip13="确认上庄" ,
  rich_car_tip14="上庄列表", 
  rich_car_tip15="庄家:" ,
  rich_car_tip16="本方:" ,
  rich_car_tip17="[fa5353]+{0}[-]", 
  rich_car_tip18="[65ffa6]{0}[-]" ,
  rich_car_tip19="轮换庄家" ,
  rich_car_tip20="连庄:      局", 
  rich_car_tip21="彩池:", 
  rich_car_tip22="筹码不足,是否前往购买？\n（1金币=100筹码）", 
  rich_car_tip23="彩金:", 
  rich_car_tip24="奖励:", 
  rich_car_tip25="至少拥有{0}筹码，才可上庄哦！", 
  rich_car_tip26="成功加入上庄队列", 
  rich_car_tip27="取消排庄", 
  rich_car_tip28="[874c38]押中以上图标奖励为[-][ff2121]20[-][874c38]倍[-]", 
  rich_car_tip29="[874c38]押中以上图标奖励为[-][ff2121]5[-][874c38]倍[-]", 
  rich_car_tip30="[ae9d8a]金币与欢乐豪车筹码兑换比例为[-][ffb31f]1:100[-][ae9d8a]，已将金币兑换成等比例的筹码，祝您游戏愉快。[-]", 
  rich_car_tip31="在线人数：{0}", 
  rich_car_tip32="[FF903F]{0}[-]", 
  rich_car_tip33="上庄条件：2,000,000,000\n区域下注上限：2,000,000,000\n玩家下注上限：2,000,000,000", 
  rich_car_tip34="当您连续20次超过时间未操作，将被请离房间！", 
  rich_car_tip35="下庄", 
  rich_car_tip36="点击查看上庄列表", 
  rich_car_tip37="点击切换趋势图", 
  rich_car_tip38="{0}秒后可以发言", 
  rich_car_tip39="庄家无法下注", 
  rich_car_tip40="您已经下注了，返回主城后，系统会帮您自动结算哦", 
  rich_car_tip41="累计赢得[fffc2a]{0}[-]筹码", 
  rich_car_tip42="取消下庄", 
  rich_car_tip43="1.盈利筹码的部分会进入彩池\n2.单注押注≥100万，才有资格分配彩池\n3.彩池分配：中奖金额为总彩池30%%，庄家分得总彩池2%%，其余玩家分得总彩池28%%。\n4.彩池额度越高，开彩池的概率越高",
  rich_car_tip44="加筹码", 
  rich_car_tip45="筹码不足" ,
  rich_car_tip46="筹码添加成功！", 
  rich_car_tip47="来到欢乐豪车，一起来膜拜！", 
  rich_car_tip48="[fa5353]+{0}[-]", 
  rich_car_tip49="[18B159]{0}[-]", 
  rich_car_tip50="您正在上庄中，离开后将自动下庄，确定离开？", 
  rich_car_tip51="个人成绩:",
  rich_car_tip52="选择上庄金额",
  rich_car_tip53="下庄成功，将在本局结束后生效！",
  rich_car_tip54="下庄成功",

  rich_car_quick1="闪，闪，闪！", 
  rich_car_quick2="我就压最后一盘！", 
  rich_car_quick3="能把本金还给我吗？" ,
  rich_car_quick4="赚大发了，哈哈哈！" ,
  rich_car_quick5="见证奇迹的时刻到了！" ,
  rich_car_quick6="是时候分一波彩池了！" ,
  num_wan = "{0}万",
  num_yi = "{0}亿" ,
    shop_desc1="VIP{0} 才可购买",

    share_title_8 = "分享游戏",
     -- 分享
    share_title_1 = "新人奖励",
    share_title_2 = "分享有奖",
    share_title_3 = "好友进阶",
    share_title_4 = "分享",
    share_title_5 = "礼品领取",
    share_title_6 = "分享规则",
    share_title_7 = "我的奖励",
    share_desc_1 = "新人注册24小时内填写好友邀请码，免费领取一次新人奖励",
    share_desc_2 = "[6D3623]每日分享朋友圈额外获得[-][6D3623]%s金币[-][6D3623]（每日一次）[-]",
    share_desc_3 = "[6D3623]每位你邀请的好友首次在公众号成功领取1元红包都会赠送你[-][6D3623]40钻石[-]",
    share_btn_1 = "免费领金币",
    share_btn_2 = "分享得大奖",
    share_btn_3 = "查看奖励",
    shar_friend_count = "当前邀请好友[9eff25]%d[-]人",
    shar_my_code = "我的邀请码:",
    shar_award_1 = "解锁15级炮",
    shar_award_2 = "充值任意金额",
    shar_award_3 = "累计充值50元",
    shar_wechat = "分享给好友/群",
    shar_wechatMoments = "分享到朋友圈",
    shar_cell_name = "分享到朋友圈",
    shar_get = "领取",
    shar_friend_big_gift = "天呐！这都能领红包？完全颠覆你的想象！...",
    shar_friend_desc = "来自《就是牛》的惊喜!正版牛牛,红包拿到手软!",
    shar_exchange_tip = "亲，快输入好友的邀请码，领取新人奖励吧！",
    shar_exchange_level = "您的注册时间超过24小时，不能领取新人奖励",
    shar_exchange_not_offical = "通过分享链接下载注册的新玩家，才可以领取新人奖励",
    shar_friend_tip = "您还没有邀请好友或好友未完成任务",
    shar_btn_tip = "[u]分享规则[/u]",
    share_input_placeholder = "请输入邀请码",

    --- 分享规则
 --- 分享规则
    share_rules_title_1 = "分享好友",
    share_rules_desc_1 = "[b97e56]点击[-][f1411e]“分享得大奖”[-][b97e56]按钮，进行[-][f1411e]微信分享[-][b97e56]。对方按照您分享链接上的“奖品领取流程”操作后，就能领取[-][f1411e]新人奖励[-][b97e56]并成为您的好友[-]",
    share_rules_title_2 = "新人奖励",
    share_rules_desc_2 = "[b97e56]只有通过分享界面[-][f1411e]下载并注册[-][b97e56]的用户在注册24小时内才能领取新人奖励。非注册用户无法领取新人奖励[-]",
    share_rules_title_3 = "邀请奖励",
    share_rules_desc_3 = "[b97e56]每个好友首次在公众号领取[-][f1411e]1元红包[-][b97e56]，可获得[-][f1411e]40钻石奖励[-][b97e56]；"
                            .. "\n玩家每天进行一次分享，还可额外获得[b97e56][-][f1411e]5000金币分享救济金[-]"
                            .. "\n[b97e56]每个邀请码每天只可被[-][f1411e]3名[-][b97e56]好友使用[-]",
  red_bag_win_desc1="(红包ID:{0})" ,
  red_bag_win_desc2="请输入红包ID" ,
  shop_btn_recharge =  "充值",
  shop_btn_free =  "免费",
  shop_gold_desc = "{0}金币",
  shop_desc2 = "VIP免费领取[fffc2a]{0}[-]次",
  shop_desc3 = "只能领取{0}次",
  shop_desc4 = "加赠[fffd68]{0}[-]金币",
  shop_desc5 = "每日限购：{0}次",
  shop_desc6 = "[ba6a2f]再充值[-][ba6a2f]{0}元[-][ba6a2f]可升至[-]",
  shop_desc7 = "{0}/{1}",
  rank_desc1 = "我的排名：",
  rank_desc2 = "[u]每天单局最高赚金排名奖励[/u]",
  rank_desc3 = "[u]本周累计总赚金排名奖励[/u]",
  rank_desc4 = "[956635]榜单总奖励[-][ff4e2b]5800万[-][956635]金币，每周一0点结算[-]",
  rank_desc5 = "盈利：",
  rank_desc6 = "名次",
  rank_desc7 = "奖励",
  rank_desc8 = "单局赚金榜",
  rank_desc9 = "累计赚金榜",
  rank_desc10 = "未上榜",
  rank_desc11 = "赚金数据实时变化，奖励将在结算后发放至邮箱",
  rank_desc12 = "[956635]榜单总奖励[-][ff4e2b]1580万[-][956635]金币，每日0点开奖[-]",
  rank_tab1 = "[FFFFFF]单局榜[-]",
  rank_tab2 = "[FFFFFF]累计榜[-]",
  rank_tab3 = "[FFFFFF]上周中奖[-]",

  rank_tab_sel1 = "[FFFFFF]单局榜[-]",
  rank_tab_sel2 = "[FFFFFF]累计榜[-]",
  rank_tab_sel3 = "[FFFFFF]上周中奖[-]",

  gold_pool_desc1 = "前往充值",
  gold_pool_desc2 = "未上榜",
  gold_pool_desc3 = "充值{0}元",
  gold_pool_desc4 = "{0}%",
  gold_pool_desc5 = "{0}-{1}",
  gold_pool_desc6 = "[ae9d8a]1、活动期间内单笔充值[-][ff931f]≥10元[-][ae9d8a]，系统将向彩池中注入一定数量的金币（与充值金额相关）。"
                    .."\n2、每次活动充值榜[-][ff931f]前50名[-][ae9d8a]的玩家可按比例瓜分彩池奖金。[-][ff931f]公式：玩家排名占比*总彩池金币。[-]"
                    .."\n[ae9d8a]3、活动只统计单笔[-][ff931f]≥10元[-][ae9d8a]以上的充值，有效累充金额相同时按时间排序，先充值的排名靠前。"
                    .."\n4、奖励将在活动结束后[-][ff931f]次日0点[-][ae9d8a]以邮件形式发放。[-]"
  ,
  
  appstore_high_pay_tips = "该档位需要到官方微信公众平台充值.（关注官方微信公众号《天添网络》后，可以在公众平台直接给游戏充值) ",
  normal_red_desc1 = "游戏规则:",
  normal_red_desc2 = "连续完成5局游戏，即可领取一次红包。",
  normal_red_desc3 = "红包金额:",
  normal_red_desc4 = "红包内有三种金额，分别为0.2元、0.5元、1元，各有33%的机会获得！",
  normal_red_desc5 = "入场限制:",
  normal_red_desc6 = "钻石少于18则无法入场。",
  normal_red_desc7 = "房间收费:",
  normal_red_desc8 = "每局游戏，比牌获胜的用户收取1钻石服务费，随牌型倍率翻倍。",
  normal_red_desc9 = "游戏结算:",
  normal_red_desc10 = "底分3钻石，3倍封顶，根据当局游戏结果玩家相互结算。 ",
  normal_red_desc11 = "牌型倍率:",
  normal_red_desc12 = "1倍    【没牛、牛一、牛二、牛三、牛四】\n2倍    【牛五、牛六、牛七、牛八】\n3倍    【牛九、牛牛、炸弹、五花牛、五小牛】",
  normal_red_tip3 = "当天购买过福袋即有机会在抢红包时额外获得6元奖励。",
  normal_red_tip4 = "x{0}",
  
  hundred_pool_desc = "（所有玩家的获利将有小额部分计入彩池）",
  hundred_pool_desc2 = "[b1906e]拖动选择上庄金额:[-][e36500]{0}[-]",
  hundred_pool_desc3 = "[b1906e]上庄至少需要[-][e36500]3000万[-][b1906e]金币[-]",
  login_award_desc1 = "奖励说明",
  login_award_desc2 = "神秘宝箱",
  login_award_desc3 = "免费领取",
  login_award_desc4 = "（所有玩家的获利将有小额部分计入彩池）",
  red_condition_desc1 = "补充钻石",

  shop_desc_new1 = "微信支付",
  shop_desc_new2 = "支付宝支付",
  normal_cow_desc1 = "{0}底分场",
  month_card_desc1 = "您已激活月卡",
  month_card_desc2 = "剩余时间          天",
  month_card_desc3 = "您每日可领取                         金币",
  month_card_desc4 = "马上获得",
  month_card_desc5 = "每日获得",
  month_card_desc6 = "300元获得至尊月卡，总共可领                              金币",
  month_card_desc7 = "提示",
  month_card_desc8 = "只需        元，立即获得120000金币",
  month_card_desc9 = "6",
  fruit_box_tip8 = "额外奖励",
  fruit_box_tip9 = "可领取",
  login_input_desc1="[u]忘记密码[/u]？",
  exchangeTip1 = "[512b22]您已成功兑换！工作人员将在[-][fe3e10]1-3个工作日[-][512b22]内将奖励发放至您游戏内的邮箱，请注意查收。[-]",
  exchangeTip2 = "适度娱乐理性消费",
  exchangeTip3 = "请适度娱乐理性消费！",
  user_bind_desc1 = "实名认证",
  user_bind_desc2 = "免费实名认证用户，获赠10000金币",
  user_bind_desc3 = "姓    名",
  user_bind_desc4 = "身份证",
  user_bind_desc5 = "用户协议说明",

  rule_content_1 = "[904c1d]1.分享方式：\n通过“分享”按钮发送您的专属链接，好友可通过链接下载并注册游戏\n[-]",
  rule_content_2_1 = "[904c1d]2.分享奖励：\n奖励1：新用户成功领取“[url=GoToTask][d71a1a][u]七日狂欢[/u][-][/url]”中的第一天任务奖励（{0}元红包），并在微信公众号[d71a1a]“天添网络”[-]成功领取红包，推广员立即获得一次“1日奖励”抽奖机会\n[-]",
  rule_content_2_2 = "[904c1d]奖励2：新用户成功领取“[url=GoToTask][d71a1a][u]七日狂欢[/u][-][/url]”中的第三天任务奖励（{0}元红包），并在微信公众号[d71a1a]“天添网络”[-]成功领取红包，推广员立即获得一次“3日奖励”抽奖机会\n[-]",
  rule_content_2_3 = "[904c1d]奖励3：新用户成功领取“[url=GoToTask][d71a1a][u]七日狂欢[/u][-][/url]”中的第七天任务奖励（{0}元红包），并在微信公众号[d71a1a]“天添网络”[-]成功领取红包，推广员立即获得一次“7日奖励”抽奖机会\n[-]",
  rule_content_2_4 = "[904c1d]奖励4：进入当月排行榜前50名的推广员，最高可以获得[fffc2a]{0}[-]元红包券\n[-]",
  rule_content_3 = "[904c1d]3.月推广排行榜规则：\n当月有效推广人数排在前面；\n有效推广人数一样的，则先到达该数的玩家排在前面\n[-]",
  rule_content_4 = "[904c1d]3.有效推广人数定义：\n您所邀请的好友完成指定游戏任务，并在微信公众号[d71a1a]“天添网络”[-]成功领取红包\n[-]",
  rule_content_5 = "[904c1d]4.排行榜为当月的排名数据，数据变动每30分钟刷新一次\n[-]",
  rule_content_6 = "[904c1d]6.月排行榜时间为：[ec81ff]每月的{0}号0点[-]开始，到[ec81ff]次月的{1}日23:59:59[-]结束\n[-]",
  rule_content_7 = "[904c1d]5.如发现有作弊、刷号行为的，一律封号处理\n[-]",
  rule_content_8 = "[904c1d]8.排行榜奖励通过邮件发放\n[-]",
  rule_content_9 = "[904c1d]9.月分享排名奖励：\n[-]",

  share_lotto_desc = "第{0}天的奖励{1}元红包",
  recharge_task_desc1 = "{0}元购买",
  recharge_task_desc2 = "激活立马获得                     金币",
  recharge_task_desc3 = "另有累计                       金币返还",
  recharge_task_desc4 = "已经累计赢取  [fef164]{0}[-]  金币",
  recharge_task_desc5 = "已购买",
  recharge_task_desc8 = "1.购买一本万利才可激活金币任务\n2.任意场：超级水果、百人大战、水果狂欢\n3.赢取金币=获得金币-押注金额",
  
}


LuaText = M

function LuaText.GetStr(module, ...)
    local cnt = select("#", ...)
    local str = module
    for i = 1, cnt, 1 do
        local search = "{" .. tostring(i - 1) .. "}"
        local val = tostring(select(i, ...))
        str = string.gsub(str, search, val)
    end
    return str
end

function LuaText.GetString(str)
    return LuaText.GetStr(LuaText[str]);
end

function LuaText.Format(str, ...)
    local module = LuaText.GetString(str);
    local cnt = select("#", ...)
    local str = module
    for i = 1, cnt, 1 do
        local search = "{" .. tostring(i - 1) .. "}"
        local val = tostring(select(i, ...))
        str = string.gsub(str, search, val)
    end
    return str
end


function LuaText.GetWhiteStr(content)
    local str = content
    str = string.gsub(str, "&#x000D;&#x000A;", "\n")
    str = string.gsub(str, "d6573e", "ffffff")
    str = string.gsub(str, "685753", "ffffff")
    return str
end